name: "Setup Workspace"
description: "This action install node and cache modules. It uses pnpm as package manager."
inputs:
  working-directory:
    description: "The working directory of your node package"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Check pnpm version
      shell: bash
      id: pnpm
      run: |
        PNPM_VERSION=${PNPM_VERSION:-7.30.5}
        PKG_JSON=$(cat package.json | jq -r '.packageManager' | awk -F@ '{print $2}')
        if [ ! -z $PKG_JSON ]; then
          PNPM_VERSION=$PKG_JSON
        fi
        if [ ! -z pnpm ]; then
          PNPM_VERSION=9.12.1
        fi
        echo "Using PNPM version $PNPM_VERSION"
        echo "version=$PNPM_VERSION" >> $GITHUB_OUTPUT

    - name: Setup PNPM
      id: pnpm_setup
      uses: pnpm/action-setup@v4.0.0
      with:
        version: ${{ steps.pnpm.outputs.version }}
        run_install: false
        package_json_file: ./package.json

    - name: Restore cached npm dependencies
      id: cache-dependencies-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          ~/.cache/Cypress # needed for the Cypress binary
        key: "dependencies-${{ hashFiles('pnpm-lock.yaml') }}"

    - name: Set up npm registry
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: .github/.nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - uses: pnpm/action-setup@v4.0.0
      id: pnpm-install
      with:
        version: 9.12.1

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Install pnpm package manager
      run: pnpm install --no-frozen-lockfile
      shell: bash

    - name: Setup pnpm config registry
      run: pnpm config set registry https://registry.npmjs.org
      shell: bash

    - name: Cache npm dependencies
      id: cache-dependencies-save
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules
          ~/.cache/Cypress # needed for the Cypress binary
          ~/.cache/
        key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

    - name: Configure git
      run: |
        git config user.name "Stormie-Bot"
        git config user.email "Stormie-Bot@users.noreply.github.com"
        git config lfs.allowincompletepush true
        git config --global init.defaultBranch main
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      shell: bash
