
name = 'examples-cloudflare-worker'
compatibility_date = '2025-05-23'
main = '/.storm/entry-0LGqoAa1pmeC5fOU1GFizPSV.ts'
account_id = 'undefined'
compatibility_flags = ['nodejs_als']
kv_namespaces = [
    { binding = 'STORAGE', id = 'storage' },
]
