
name = 'storm-stack'
compatibility_date = '2025-06-24'
main = '.storm/entry-0LGqoAa1pmeC5fOU1GFizPSV.ts'
compatibility_flags = ['nodejs_als']
kv_namespaces = [
    { binding = 'STORAGE', id = 'storage' },
]
