onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@deepkit/type-compiler"
  - "@swc/core"
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - protobufjs
  - sharp
  - utf-8-validate

packages:
  - "tools/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@ast-grep/napi": ^0.36.2
  "@biomejs/biome": ^1.9.4
  "@cloudflare/unenv-preset": 2.3.1
  "@deepkit/injector": ^1.0.5
  "@deepkit/type-compiler": ^1.0.5
  "@donedeal0/superdiff": ^3.1.2
  "@eslint/compat": ^1.2.8
  "@eslint/config-inspector": ^0.7.1
  "@ls-lint/ls-lint": ^2.3.0
  "@ltd/j-toml": ^1.38.0
  "@microsoft/api-extractor": ^7.52.3
  "@nuxt/kit": ^3.16.2
  "@nuxt/schema": ^3.16.2
  "@opentelemetry/api-logs": ^0.200.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.200.0
  "@opentelemetry/otlp-exporter-base": ^0.200.0
  "@opentelemetry/resources": ^1.30.1
  "@opentelemetry/sdk-logs": ^0.200.0
  "@opentelemetry/semantic-conventions": ^1.32.0
  "@sentry/core": ^9.12.0
  "@sentry/node": ^9.12.0
  "@sentry/types": ^9.12.0
  "@storm-stack/core": 0.4.0
  "@storm-stack/log-stream": 0.3.0
  "@storm-stack/nx": 0.3.0
  "@taplo/cli": ^0.7.0
  "@types/eslint": ^9.6.1
  "@types/eslint__js": ^8.42.3
  "@types/invariant": ^2.2.37
  "@types/jest": 29.5.14
  "@types/react": "npm:types-react@rc"
  "@types/react-dom": "npm:types-react-dom@rc"
  "@types/node": ^22.14.1
  "@nx/devkit": 20.7.2
  "@nx/eslint-plugin": 20.7.2
  "@nx/jest": 20.7.2
  "@nx/js": 20.7.2
  "@nx/plugin": 20.7.2
  "@nx/react": 20.7.2
  "@nx/workspace": 20.7.2
  "@storm-software/build-tools": latest
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/prettier": latest
  "@storm-software/markdownlint": latest
  "@storm-software/esbuild": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/workspace-tools": latest
  "@stryke/env": latest
  "@stryke/fs": latest
  "@stryke/helpers": latest
  "@stryke/http": latest
  "@stryke/unique-id": latest
  "@stryke/json": latest
  "@stryke/path": latest
  "@stryke/types": latest
  "@stryke/hash": latest
  "@stryke/string-format": latest
  "@stryke/convert": latest
  "@stryke/type-checks": latest
  "@stryke/cli": latest
  "@swc-node/register": ^1.10.10
  "@swc/core": ^1.11.20
  "@swc/wasm": ^1.11.20
  "@swc/helpers": ^0.5.17
  "@typescript-eslint/scope-manager": ^8.29.1
  "@typescript-eslint/utils": ^8.29.1
  bundle-require: ^5.1.0
  c12: ^3.0.3
  chalk-template: ^1.1.0
  commander: ^13.1.0
  diff-match-patch: ^1.0.5
  eslint: ^9.24.0
  eslint-doc-generator: ^2.1.2
  eslint-plugin-eslint-plugin: 6.4.0
  eslint-plugin-i18n-text: 1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: 2.1.0
  globals: ^15.15.0
  invariant: ^2.2.4
  jest-worker: ^29.7.0
  jsonc-eslint-parser: 2.4.0
  lefthook: ^1.11.9
  log4brains: ^1.1.0
  magic-string: ^0.30.17
  prettier: ^3.5.3
  nx: 20.7.2
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-environment-node: 29.7.0
  react: 19.0.0-rc-f6cce072-20240723
  react-dom: 19.0.0-rc-f6cce072-20240723
  react-native: 0.75.4
  sherif: ^1.5.0
  ts-jest: ^29.3.2
  ts-morph: ^25.0.1
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: 8.4.0
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  tsx: ^4.19.3
  typescript: ~5.7.3
  esbuild: 0.25.2
  rollup: ^4.40.0
  rolldown: ^1.0.0-beta.7
  unbuild: ^3.5.0
  unenv: npm:unenv-nightly
  unimport: ^4.2.0
  unstorage: ^1.15.0
  untyped: "1.5.2"
  verdaccio: 6.1.2
  vite: ^6.2.6
  defu: "^6.1.4"
  jiti: "^2.4.2"
  eslint-flat-config-utils: 2.0.1
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
  zx: ^8.5.2
overrides:
  "@storm-stack/core": workspace:*
  "@storm-stack/biome": workspace:*
  "@storm-stack/log-console": workspace:*
  "@storm-stack/log-storage": workspace:*
  "@storm-stack/log-otel": workspace:*
  "@storm-stack/log-sentry": workspace:*
  "@storm-stack/log-stream": workspace:*
  "@storm-stack/nx": workspace:*
  "@storm-stack/plugin-http": workspace:*
  "@storm-stack/preset-cli": workspace:*
  "@storm-stack/preset-cloudflare-worker": workspace:*
  "@storm-stack/plugin-node": workspace:*
  "@storm-stack/tools-config": workspace:*
  "@storm-stack/tools-nx": workspace:*
  "@storm-stack/tools-readme-templates": workspace:*
  "@storm-stack/tools-scripts": workspace:*
  "debug": ">=4.3.7"
  "eslint-config-storm-stack": workspace:*
  "eslint-plugin-storm-stack": workspace:*
  "follow-redirects": ">=1.15.9"
  "got": ">=14.4.2"
  "ip": ">=2.0.1"
  "loader-utils": ">=3.3.1"
  "markdown-it": ">=14.1.0"
  "node-fetch": ">=3.3.2"
  "nth-check": ">=2.1.1"
  "parse-path": ">=7.0.0"
  "parse-url": ">=9.2.0"
  "postcss": ">=8.4.47"
  "shell-quote": ">=1.8.1"
  "simple-git": ">=3.27.0"
