packages:
  - "tools/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@microsoft/api-extractor": ^7.48.1
  "@types/jest": 29.5.13
  "@types/react": "npm:types-react@rc"
  "@types/react-dom": "npm:types-react-dom@rc"
  "@types/node": ^22.10.2
  "@nx/devkit": ^20.5.0
  "@nx/eslint-plugin": ^20.5.0
  "@nx/jest": ^20.5.0
  "@nx/js": ^20.5.0
  "@nx/plugin": ^20.5.0
  "@nx/react": ^20.5.0
  "@nx/workspace": ^20.5.0
  "@storm-software/build-tools": latest
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/prettier": latest
  "@storm-software/markdownlint": latest
  "@storm-software/esbuild": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/workspace-tools": latest
  "@stryke/env": latest
  "@stryke/fs": latest
  "@stryke/helpers": latest
  "@stryke/unique-id": latest
  "@stryke/json": latest
  "@stryke/path": latest
  "@stryke/types": latest
  "@stryke/hash": latest
  "@stryke/string-format": latest
  "@swc-node/register": ^1.10.9
  "@swc/core": ^1.7.26
  "@swc/wasm": ^1.10.1
  "@swc/helpers": ^0.5.13
  eslint: ^9.20.1
  prettier: ^3.5.2
  nx: ^20.5.0
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-environment-node: 29.7.0
  react: 19.0.0-rc-f6cce072-20240723
  react-dom: 19.0.0-rc-f6cce072-20240723
  react-native: 0.75.4
  tsup: ^8.3.5
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  typescript: ~5.7.3
  esbuild: 0.25.0
  rollup: ^4.28.1
  rolldown: ^1.0.0-beta.1
  unbuild: ^3.3.0
  untyped: "^1.5.2"
  vite: ^6.0.4
  defu: "^6.1.4"
  jiti: "^2.4.2"
  eslint-flat-config-utils: ^2.0.1
