shamefullyHoist: true
autoInstallPeers: true
strictPeerDependencies: false
linkWorkspacePackages: true
preferWorkspacePackages: true
registry: https://registry.npmjs.org/
gitChecks: true
publishBranch: main

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@deepkit/type-compiler'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - protobufjs
  - sharp
  - utf-8-validate
  - unrs-resolver

packages:
  - tools/**
  - packages/**
  - examples/**

catalog:
  '@ast-grep/napi': ^0.37.0
  '@biomejs/biome': ^1.9.4
  '@cloudflare/unenv-preset': 2.3.1
  '@cloudflare/workers-types': ^4.20250430.0
  '@deepkit/type': ^1.0.5
  '@deepkit/core': ^1.0.5
  '@deepkit/type-compiler': ^1.0.5
  '@donedeal0/superdiff': ^3.1.2
  '@eslint/compat': ^1.2.8
  '@eslint/config-inspector': ^0.7.1
  '@ls-lint/ls-lint': ^2.3.0
  '@ltd/j-toml': ^1.38.0
  '@microsoft/api-extractor': ^7.52.6
  '@nuxt/kit': ^3.17.1
  '@nuxt/schema': ^3.17.1
  '@opentelemetry/api-logs': ^0.200.0
  '@opentelemetry/exporter-logs-otlp-http': ^0.200.0
  '@opentelemetry/otlp-exporter-base': ^0.200.0
  '@opentelemetry/resources': ^2.0.0
  '@opentelemetry/sdk-logs': ^0.200.0
  '@opentelemetry/semantic-conventions': ^1.32.0
  '@sentry/core': ^9.14.0
  '@sentry/node': ^9.14.0
  '@sentry/types': ^9.14.0
  '@taplo/cli': ^0.7.0
  '@types/eslint': ^9.6.1
  '@types/eslint__js': ^8.42.3
  '@types/invariant': ^2.2.37
  '@types/jest': 29.5.14
  '@types/react': npm:types-react@rc
  '@types/react-dom': npm:types-react-dom@rc
  '@types/node': ^22.15.3
  '@nx/devkit': 20.8.1
  '@nx/eslint-plugin': 20.8.1
  '@nx/jest': 20.8.1
  '@nx/js': 20.8.1
  '@nx/plugin': 20.8.1
  '@nx/react': 20.8.1
  '@nx/workspace': 20.8.1
  '@storm-software/build-tools': 0.144.22
  '@storm-software/config': 1.113.26
  '@storm-software/config-tools': 1.163.27
  '@storm-software/cspell': 0.21.22
  '@storm-software/git-tools': 2.104.49
  '@storm-software/linting-tools': 1.119.62
  '@storm-software/eslint': 0.148.22
  '@storm-software/prettier': 0.45.31
  '@storm-software/markdownlint': 0.18.37
  '@storm-software/esbuild': 0.35.13
  '@storm-software/unbuild': 0.41.23
  '@storm-software/untyped': 0.11.59
  '@storm-software/testing-tools': 1.104.83
  '@storm-software/tsconfig': 0.35.73
  '@storm-software/workspace-tools': 1.267.22
  '@stryke/env': 0.6.5
  '@stryke/fs': 0.12.1
  '@stryke/helpers': 0.5.2
  '@stryke/http': 0.8.0
  '@stryke/unique-id': 0.2.6
  '@stryke/url': 0.1.0
  '@stryke/json': 0.8.1
  '@stryke/path': 0.4.11
  '@stryke/types': 0.8.1
  '@stryke/hash': 0.9.2
  '@stryke/string-format': 0.4.2
  '@stryke/convert': 0.1.5
  '@stryke/type-checks': 0.3.2
  '@stryke/cli': 0.9.0
  '@swc-node/register': ^1.10.10
  '@swc/core': ^1.11.22
  '@swc/wasm': ^1.11.24
  '@swc/helpers': ^0.5.17
  '@typescript-eslint/scope-manager': ^8.31.1
  '@typescript-eslint/types': ^8.31.1
  '@typescript-eslint/utils': ^8.31.1
  bundle-require: ^5.1.0
  c12: ^3.0.3
  chalk-template: ^1.1.0
  commander: ^13.1.0
  diff-match-patch: ^1.0.5
  eslint: ^9.25.1
  eslint-doc-generator: ^2.1.2
  eslint-plugin-eslint-plugin: 6.4.0
  eslint-plugin-i18n-text: 1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: 2.1.0
  globals: ^15.15.0
  invariant: ^2.2.4
  jest-worker: ^29.7.0
  jsonc-eslint-parser: 2.4.0
  lefthook: ^1.11.12
  log4brains: ^1.1.0
  magic-string: ^0.30.17
  magicast: ^0.3.5
  mlly: ^1.7.4
  prettier: ^3.5.3
  nx: 20.8.1
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-environment-node: 29.7.0
  react: 19.0.0-rc-f6cce072-20240723
  react-dom: 19.0.0-rc-f6cce072-20240723
  react-native: 0.75.4
  sherif: ^1.5.0
  ts-jest: ^29.3.2
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: 8.4.0
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  tsx: ^4.19.4
  typescript: ~5.7.3
  esbuild: 0.25.3
  rollup: ^4.40.1
  rolldown: ^1.0.0-beta.8
  unbuild: ^3.5.0
  unenv: npm:unenv-nightly
  unimport: ^4.2.0
  unstorage: ^1.16.0
  untyped: 1.5.2
  verdaccio: 6.1.2
  vite: ^6.3.4
  defu: ^6.1.4
  jiti: ^2.4.2
  eslint-flat-config-utils: 2.0.1
  zod: ^3.24.3
  zod-validation-error: ^3.4.0
  zx: ^8.5.3

overrides:
  '@storm-stack/types': workspace:*
  '@storm-stack/core': workspace:*
  '@storm-stack/biome': workspace:*
  '@storm-stack/log-console': workspace:*
  '@storm-stack/log-storage': workspace:*
  '@storm-stack/log-otel': workspace:*
  '@storm-stack/log-sentry': workspace:*
  '@storm-stack/log-stream': workspace:*
  '@storm-stack/nx': workspace:*
  '@storm-stack/plugin-http': workspace:*
  '@storm-stack/preset-cli': workspace:*
  '@storm-stack/preset-cloudflare-worker': workspace:*
  '@storm-stack/plugin-node': workspace:*
  '@storm-stack/tools-config': workspace:*
  '@storm-stack/tools-nx': workspace:*
  '@storm-stack/tools-readme-templates': workspace:*
  '@storm-stack/tools-scripts': workspace:*
  debug: '>=4.3.7'
  eslint-config-storm-stack: workspace:*
  eslint-plugin-storm-stack: workspace:*
  follow-redirects: '>=1.15.9'
  got: '>=14.4.2'
  ip: '>=2.0.1'
  loader-utils: '>=3.3.1'
  markdown-it: '>=14.1.0'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  postcss: '>=8.4.47'
  shell-quote: '>=1.8.1'
  simple-git: '>=3.27.0'

patchedDependencies:
  '@deepkit/type-compiler@1.0.5': patches/@deepkit__type-compiler@1.0.5.patch
  '@deepkit/type@1.0.5': patches/@deepkit__type@1.0.5.patch
