linkWorkspacePackages: true
preferWorkspacePackages: true

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@deepkit/type-compiler"
  - "@swc/core"
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - protobufjs
  - sharp
  - utf-8-validate
  - unrs-resolver

packages:
  - "tools/*"
  - "packages/*"
  - "examples/*"

catalog:
  "@ast-grep/napi": ^0.37.0
  "@biomejs/biome": ^1.9.4
  "@cloudflare/unenv-preset": 2.3.1
  "@cloudflare/workers-types": ^4.20250505.0
  "@deepkit/type": ^1.0.5
  "@deepkit/core": ^1.0.5
  "@deepkit/type-compiler": ^1.0.5
  "@donedeal0/superdiff": ^3.1.2
  "@eslint/compat": ^1.2.9
  "@eslint/config-inspector": ^0.7.1
  "@ls-lint/ls-lint": ^2.3.0
  "@ltd/j-toml": ^1.38.0
  "@microsoft/api-extractor": ^7.52.7
  "@nuxt/kit": ^3.17.1
  "@nuxt/schema": ^3.17.1
  "@opentelemetry/api-logs": ^0.200.0
  "@opentelemetry/exporter-logs-otlp-grpc": ^0.200.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.200.0
  "@opentelemetry/otlp-exporter-base": ^0.200.0
  "@opentelemetry/otlp-grpc-exporter-base": ^0.200.0
  "@opentelemetry/resources": ^2.0.0
  "@opentelemetry/sdk-logs": ^0.200.0
  "@opentelemetry/semantic-conventions": ^1.32.0
  "@sentry/core": ^9.15.0
  "@sentry/node": ^9.15.0
  "@sentry/types": ^9.15.0
  "@taplo/cli": ^0.7.0
  "@types/eslint": ^9.6.1
  "@types/eslint__js": ^8.42.3
  "@types/invariant": ^2.2.37
  "@types/jest": 29.5.14
  "@types/react": npm:types-react@rc
  "@types/react-dom": npm:types-react-dom@rc
  "@types/node": ^22.15.3
  "@nx/devkit": 21.0.3
  "@nx/eslint-plugin": 21.0.3
  "@nx/jest": 21.0.3
  "@nx/js": 21.0.3
  "@nx/plugin": 21.0.3
  "@nx/react": 21.0.3
  "@nx/workspace": 21.0.3
  "@storm-software/build-tools": latest
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/prettier": latest
  "@storm-software/markdownlint": latest
  "@storm-software/esbuild": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/workspace-tools": latest
  "@stryke/env": ^0.6.6
  "@stryke/fs": ^0.12.2
  "@stryke/helpers": ^0.5.3
  "@stryke/http": ^0.8.1
  "@stryke/unique-id": ^0.2.7
  "@stryke/url": ^0.1.1
  "@stryke/json": ^0.8.2
  "@stryke/path": ^0.4.14
  "@stryke/types": ^0.8.2
  "@stryke/hash": ^0.9.3
  "@stryke/string-format": ^0.4.7
  "@stryke/convert": ^0.1.6
  "@stryke/type-checks": ^0.3.3
  "@stryke/cli": ^0.10.2
  "@swc-node/register": ^1.10.10
  "@swc/core": ^1.11.22
  "@swc/wasm": ^1.11.24
  "@swc/helpers": ^0.5.17
  "@typescript-eslint/scope-manager": ^8.31.1
  "@typescript-eslint/types": ^8.31.1
  "@typescript-eslint/utils": ^8.31.1
  bundle-require: ^5.1.0
  c12: ^3.0.3
  chalk-template: ^1.1.0
  diff-match-patch: ^1.0.5
  eslint: ^9.26.0
  eslint-doc-generator: ^2.1.2
  eslint-plugin-eslint-plugin: 6.4.0
  eslint-plugin-i18n-text: 1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: 2.1.0
  globals: ^15.15.0
  handlebars: ^4.7.8
  invariant: ^2.2.4
  jest-worker: ^29.7.0
  jsonc-eslint-parser: 2.4.0
  lefthook: ^1.11.12
  log4brains: ^1.1.0
  magic-string: ^0.30.17
  magicast: ^0.3.5
  mlly: ^1.7.4
  prettier: ^3.5.3
  nx: 21.0.3
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-environment-node: 29.7.0
  react: 19.0.0-rc-f6cce072-20240723
  react-dom: 19.0.0-rc-f6cce072-20240723
  react-native: 0.75.4
  sherif: ^1.5.0
  ts-jest: ^29.3.2
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: 8.4.0
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  tsx: ^4.19.4
  typedoc: "0.25.12"
  typedoc-plugin-frontmatter: ^1.3.0
  typedoc-plugin-markdown: 3.17.1
  esbuild: 0.25.3
  rollup: ^4.40.1
  rolldown: ^1.0.0-beta.8
  unbuild: ^3.5.0
  unenv: npm:unenv-nightly
  unimport: ^4.2.0
  unstorage: ^1.16.0
  untyped: 1.5.2
  verdaccio: 6.1.2
  vite: ^6.3.4
  defu: ^6.1.4
  jiti: ^2.4.2
  eslint-flat-config-utils: 2.0.1
  zod: ^3.24.4
  zod-validation-error: ^3.4.0
  zx: ^8.5.3

overrides:
  "@storm-stack/types": workspace:*
  "@storm-stack/core": workspace:*
  "@storm-stack/devkit": workspace:*
  "@storm-stack/biome": workspace:*
  "@storm-stack/plugin-log-console": workspace:*
  "@storm-stack/plugin-log-storage": workspace:*
  "@storm-stack/plugin-log-otel": workspace:*
  "@storm-stack/plugin-log-sentry": workspace:*
  "@storm-stack/plugin-storage-fs": workspace:*
  "@storm-stack/plugin-storage-cloudflare-kv": workspace:*
  "@storm-stack/nx": workspace:*
  "@storm-stack/preset-cli": workspace:*
  "@storm-stack/preset-cloudflare-worker": workspace:*
  "@storm-stack/tools-config": workspace:*
  "@storm-stack/tools-nx": workspace:*
  "@storm-stack/tools-readme-templates": workspace:*
  "@storm-stack/tools-scripts": workspace:*
  debug: ">=4.3.7"
  eslint-config-storm-stack: workspace:*
  eslint-plugin-storm-stack: workspace:*
  follow-redirects: ">=1.15.9"
  got: ">=14.4.2"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  postcss: ">=8.4.47"
  shell-quote: ">=1.8.1"
  simple-git: ">=3.27.0"

patchedDependencies:
  "@deepkit/type-compiler@1.0.5": patches/@deepkit__type-compiler@1.0.5.patch
  "@deepkit/type@1.0.5": patches/@deepkit__type@1.0.5.patch
