packages:
  - tools/*
  - packages/*
  - examples/*
catalog:
  "@alloy-js/babel-plugin": ^0.2.1
  "@alloy-js/babel-plugin-jsx-dom-expressions": ^0.39.1
  "@alloy-js/babel-preset": ^0.2.1
  "@alloy-js/cli": ^0.21.0
  "@alloy-js/core": ^0.21.0
  "@alloy-js/json": ^0.21.0
  "@alloy-js/markdown": ^0.21.0
  "@alloy-js/rollup-plugin": ^0.1.0
  "@alloy-js/typescript": ^0.21.0
  "@babel/core": ^7.28.5
  "@babel/generator": ^7.28.5
  "@babel/helper-module-imports": ^7.27.1
  "@babel/helper-module-transforms": ^7.28.3
  "@babel/helper-plugin-utils": ^7.27.1
  "@babel/helper-simple-access": ^7.27.1
  "@babel/parser": ^7.28.5
  "@babel/plugin-proposal-decorators": ^7.28.0
  "@babel/plugin-syntax-class-properties": ^7.12.13
  "@babel/plugin-syntax-import-assertions": ^7.27.1
  "@babel/plugin-syntax-typescript": ^7.27.1
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/plugin-transform-export-namespace-from": ^7.27.1
  "@babel/plugin-transform-react-jsx": ^7.27.1
  "@babel/plugin-transform-typescript": ^7.28.5
  "@babel/preset-typescript": ^7.28.5
  "@babel/preset-react": ^7.28.4
  "@babel/template": ^7.27.2
  "@babel/traverse": ^7.28.5
  "@babel/types": ^7.28.5
  "@biomejs/biome": ^1.9.4
  "@clack/prompts": ^0.11.0
  "@cloudflare/unenv-preset": 2.7.10
  "@cloudflare/vite-plugin": ^1.14.2
  "@deepkit/core": 1.0.5
  "@deepkit/type": 1.0.5
  "@deepkit/type-compiler": 1.0.5
  "@deepkit/type-spec": 1.0.1
  "@donedeal0/superdiff": ^3.1.2
  "@eslint/compat": ^1.4.1
  "@eslint/config-inspector": ^0.7.1
  "@ls-lint/ls-lint": ^2.3.1
  "@ltd/j-toml": ^1.38.0
  "@microsoft/api-extractor": ^7.55.0
  "@microsoft/tsdoc": ^0.16.0
  "@microsoft/tsdoc-config": ^0.18.0
  "@rollup/plugin-alias": ^5.1.1
  "@rollup/plugin-babel": ^6.1.0
  "@rollup/plugin-commonjs": ^28.0.9
  "@rollup/plugin-node-resolve": ^16.0.3
  "@rspack/cli": ^1.6.3
  "@rspack/core": ^1.6.3
  "@types/babel__core": ^7.20.5
  "@types/babel__helper-module-imports": ^7.18.3
  "@types/babel__helper-plugin-utils": ^7.10.3
  "@types/babel__template": ^7.4.4
  "@types/babel__traverse": ^7.28.0
  "@vue/reactivity": ^3.5.24
  astro: ^5.13.5
  babel-plugin-parameter-decorator: ^1.0.16
  conventional-changelog-storm-software: latest
  esbuild-plugin-babel: ^0.2.3
  esbuild-plugin-tsc: ^0.5.0
  rolldown: ^1.0.0-beta.50
  rollup: ^4.53.2
  rollup-plugin-ts-paths: ^1.0.5
  rollup-plugin-typescript2: ^0.36.0
  vite: ^7.1.5
  webpack: ^5.102.1
  "@nuxt/kit": ^4.2.1
  "@nuxt/schema": ^4.2.1
  "@opentelemetry/api-logs": ^0.208.0
  "@opentelemetry/exporter-logs-otlp-grpc": ^0.208.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.208.0
  "@opentelemetry/otlp-exporter-base": ^0.208.0
  "@opentelemetry/otlp-grpc-exporter-base": ^0.208.0
  "@opentelemetry/resources": ^2.2.0
  "@opentelemetry/sdk-logs": ^0.208.0
  "@opentelemetry/semantic-conventions": ^1.38.0
  "@sentry/core": ^9.46.0
  "@sentry/node": ^9.46.0
  "@sentry/types": ^9.46.0
  "@taplo/cli": ^0.7.0
  "@types/eslint": ^9.6.1
  "@types/eslint__js": ^8.42.3
  "@types/jest": 30.0.0
  "@types/react": npm:@types/react@ts5.9
  "@types/react-dom": npm:@types/react-dom@ts5.9
  "@types/node": ^22.19.1
  "@types/diff-match-patch": ^1.0.36
  "@nx/devkit": 21.6.8
  "@nx/esbuild": 21.6.8
  "@nx/eslint-plugin": 21.6.8
  "@nx/jest": 21.6.8
  "@nx/js": 21.6.8
  "@nx/plugin": 21.6.8
  "@nx/react": 21.6.8
  "@nx/workspace": 21.6.8
  "@storm-software/build-tools": latest
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/pnpm-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/prettier": latest
  "@storm-software/markdownlint": latest
  "@storm-software/esbuild": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/tsdoc": latest
  "@storm-software/workspace-tools": latest
  "@stryke/env": ^0.20.12
  "@stryke/fs": ^0.32.11
  "@stryke/helpers": ^0.9.3
  "@stryke/http": ^0.11.2
  "@stryke/unique-id": ^0.3.6
  "@stryke/url": ^0.2.5
  "@stryke/json": ^0.9.4
  "@stryke/path": ^0.19.0
  "@stryke/types": ^0.10.1
  "@stryke/hash": ^0.12.1
  "@stryke/string-format": ^0.12.1
  "@stryke/convert": ^0.6.1
  "@stryke/type-checks": ^0.3.11
  "@stryke/cli": ^0.12.5
  "@stryke/capnp": ^0.12.19
  "@swc-node/register": ^1.11.1
  "@swc/core": ^1.15.2
  "@swc/wasm": ^1.15.2
  "@swc/helpers": ^0.5.17
  "@types/semver": ^7.7.1
  "@typescript-eslint/scope-manager": ^8.46.4
  "@typescript-eslint/types": ^8.46.4
  "@typescript-eslint/utils": ^8.46.4
  "@typescript/vfs": ^1.6.2
  "@vitejs/plugin-react": ^5.1.1
  babel-dead-code-elimination: ^1.0.10
  babel-plugin-react-compiler: 19.1.0-rc.3
  bundle-require: ^5.1.0
  c12: ^3.3.2
  cfonts: ^3.3.1
  chalk: ^5.6.2
  chalk-template: ^1.1.2
  date-fns: ^4.1.0
  diff-match-patch: ^1.0.5
  eslint: ^9.39.1
  eslint-doc-generator: ^2.3.0
  eslint-plugin-eslint-plugin: 6.5.0
  eslint-plugin-i18n-text: 1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-flat-config-utils: 2.1.4
  eslint-typegen: 2.3.0
  github-slugger: ^2.0.0
  globals: ^15.15.0
  handlebars: ^4.7.8
  jsonc-eslint-parser: 2.4.1
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  magic-string: ^0.30.21
  memfs: ^4.51.0
  minimatch: ^10.1.1
  nanotar: ^0.2.0
  prettier: ^3.6.2
  nx: 21.5.3
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-environment-node: 30.2.0
  jest-worker: 30.2.0
  jest-util: 30.2.0
  react: 19.2.0-canary-4123f6b7-20250826
  react-dom: 19.2.0-canary-4123f6b7-20250826
  react-native: 0.75.4
  sherif: ^1.9.0
  tinycolor2: ^1.6.0
  ts-jest: 29.4.5
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: 8.4.0
  copyfiles: ^2.4.1
  rimraf: ^6.1.0
  tsx: ^4.20.6
  typedoc: 0.28.14
  typedoc-plugin-frontmatter: ^1.3.0
  typedoc-plugin-markdown: 4.9.0
  esbuild: ^0.27.0
  unbuild: ^3.6.1
  unenv: npm:unenv-nightly
  unimport: ^4.2.0
  unplugin: ^2.3.10
  unionfs: ^4.6.0
  unstorage: ^1.17.2
  untyped: 1.5.2
  uqr: ^0.1.2
  verdaccio: 6.2.1
  defu: ^6.1.4
  jiti: ^2.6.1
  wrangler: ^4.47.0
  zx: ^8.8.5
linkWorkspacePackages: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@deepkit/type-compiler"
  - "@swc/core"
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd
overrides:
  "@storm-stack/types": workspace:*
  "@storm-stack/core": workspace:*
  "@storm-stack/devkit": workspace:*
  "@storm-stack/biome": workspace:*
  "@storm-stack/tsdoc": workspace:*
  "@storm-stack/tsconfig": workspace:*
  "@storm-stack/plugin-date": workspace:*
  "@storm-stack/plugin-env": workspace:*
  "@storm-stack/plugin-error": workspace:*
  "@storm-stack/plugin-node": workspace:*
  "@storm-stack/plugin-cli": workspace:*
  "@storm-stack/plugin-cloudflare": workspace:*
  "@storm-stack/plugin-log-console": workspace:*
  "@storm-stack/plugin-log-storage": workspace:*
  "@storm-stack/plugin-log-otel": workspace:*
  "@storm-stack/plugin-log-sentry": workspace:*
  "@storm-stack/plugin-react": workspace:*
  "@storm-stack/plugin-storage-fs": workspace:*
  "@storm-stack/plugin-storage-cloudflare-kv": workspace:*
  "@storm-stack/plugin-storage-cloudflare-r2": workspace:*
  "@storm-stack/plugin-storage-s3": workspace:*
  "@storm-stack/cli": workspace:*
  "@storm-stack/nx": workspace:*
  "@storm-stack/tools-config": workspace:*
  "@storm-stack/tools-nx": workspace:*
  "@storm-stack/tools-readme-templates": workspace:*
  "@storm-stack/tools-scripts": workspace:*
  eslint-config-storm-stack: workspace:*
  eslint-plugin-storm-stack: workspace:*
  debug: ">=4.3.7"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.2"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  postcss: ">=8.4.47"
  shell-quote: ">=1.8.1"
  simple-git: ">=3.27.0"
patchedDependencies:
  "@deepkit/type": patches/@deepkit__type.patch
  "@deepkit/type-compiler": patches/@deepkit__type-compiler.patch
  "@deepkit/type-spec": patches/@deepkit__type-spec.patch
  "@deepkit/core": patches/@deepkit__core.patch
  "@alloy-js/babel-plugin-jsx-dom-expressions": patches/@alloy-js__babel-plugin-jsx-dom-expressions.patch
  "@alloy-js/core": patches/@alloy-js__core.patch
preferWorkspacePackages: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@storm-software/*"
  - "@stryke/*"
  - "@storm-stack/*"
