[project]
name = "storm-stack"
revision = "1.0"
# extends = [ "./subdir1" ]

[profiles.default]
SENTRY_DSN = { description = "Sentry DSN URL Secret", required = true, default = "https://example.sentry.io/123456" }

[profiles.development]
SENTRY_DSN = { description = "Sentry DSN URL Secret", required = true, default = "https://example.sentry.io/123456" }
