/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import "storm:init";

import { getSink as getConsoleSink } from "@storm-stack/log-console";
import { getSink as getSentrySink } from "@storm-stack/log-sentry";
import { builder } from "storm:app";
import { getCity as handle } from "../src/index";

export default builder({
  name: "examples-node-app",
  log: [
    { handle: getConsoleSink(), logLevel: "debug" },
    { handle: getSentrySink(), logLevel: "error" }
  ]
})
  .handler(handle)
  .build();
