/* -------------------------------------------------------------------

                  ⚡ Storm Software - Storm Stack

 This code was released as part of the Storm Stack project. Storm Stack
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/storm-stack.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/storm-stack
 Documentation:            https://docs.stormsoftware.com/projects/storm-stack
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

export function getBaseFileHeader(): string {
  return `
// Generated with Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically
`;
}

export function getFileHeader(
  directive: string | null = "",
  prettierIgnore = false
): string {
  if (directive && process.env.STORM_STACK_LOCAL) {
    directive = directive.replaceAll(
      "@storm-stack/types",
      "../../dist/packages/types"
    );
  }

  return `/* eslint-disable */
// biome-ignore lint: disable
${prettierIgnore ? `// prettier-ignore` : ""}${directive ? `\n\n${directive}\n` : "\n"}
${getBaseFileHeader()}

`;
}
