/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import "@cloudflare/unenv-preset/polyfill/performance";
import { handler as handle } from "../src/index";

import { getSink } from "@storm-stack/log-console";
import { WorkerEntrypoint } from "cloudflare:workers";
import { builder } from "./runtime/app";

const handleRequest = builder({
  name: "examples-cloudflare-worker",
  log: { handle: getSink(), logLevel: "debug" }
})
  .handler(handle)
  .build();

export default class extends WorkerEntrypoint {
  fetch(req, env, ctx) {
    return handleRequest({ req, env, ctx });
  }
}
