/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import "@cloudflare/unenv-preset/polyfill/performance";
import { deserialize, serialize } from "@deepkit/type";
import { handler as handle } from "../src/index";
import { wrap } from "./runtime/app";
import { StormRequest } from "./runtime/request";
import { StormResponse } from "./runtime/response";

const handleRequest = wrap(handle, {
  deserializer: (req: Request) => new StormRequest(deserialize(req)),
  serializer: result => StormResponse.create(serialize(result))
});

export default {
  async fetch(req: Request) {
    return handleRequest(req);
  }
};
