/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import { withContext } from "../../../runtime/app";
import {
  colors,
  parseArgs,
  prompt,
  renderBanner,
  renderFooter
} from "../../../runtime/cli";
import { isInteractive, isMinimal } from "../../../runtime/env";
import handle from "./handle";
import { renderUsage } from "./usage";

export interface CompletionsBashPayload {
  help: boolean;
  version: boolean;
  interactive: boolean;
  noInteractive: boolean;
  noBanner: boolean;
  verbose: boolean;
  script: string | true;
  config: string | true;
}

const handleCommand = withContext<CompletionsBashPayload>(handle);

/**
 * The entry point for the CLI Completions - Bash Shell command.
 */
async function handler() {
  try {
    const args = parseArgs(process.argv.slice(3), {
      boolean: [
        "help",
        "h",
        "?",
        "version",
        "v",
        "interactive",
        "i",
        "interact",
        "no-interactive",
        "no-interact",
        "no-banner",
        "",
        "verbose",
        "v"
      ],
      alias: {
        help: ["help", "HELP", "h", "H", "?", "?"],
        version: ["version", "VERSION", "v", "V"],
        interactive: [
          "interactive",
          "INTERACTIVE",
          "i",
          "I",
          "interact",
          "INTERACT"
        ],
        noInteractive: [
          "no-interactive",
          "NO-INTERACTIVE",
          "no-interact",
          "NO-INTERACT"
        ],
        noBanner: ["no-banner", "NO-BANNER"],
        verbose: ["verbose", "VERBOSE", "v", "V"],
        script: ["script", "SCRIPT", "s", "S"],
        config: ["config", "CONFIG", "c", "C"]
      }
    });

    if (args["version"] || args["v"]) {
      console.log($storm.vars.APP_VERSION);
    } else {
      const isVerbose =
        args["verbose"] ?? Boolean(process.env.EXAMPLES_CLI_VERBOSE);
      const isPromptEnabled =
        args["interactive"] !== false &&
        args["no-interactive"] !== true &&
        Boolean(process.env.EXAMPLES_CLI_INTERACTIVE) &&
        isInteractive &&
        !isMinimal;

      if (args["no-banner"] !== true && !isMinimal) {
        console.log(
          renderBanner(
            "CLI Completions - Bash Shell Command",
            "Generates a Bash shell completion script for the Examples CLI App CLI application."
          )
        );
        console.log("");
      }

      if (args["help"] || args["h"] || args["?"]) {
        console.log(renderUsage("full"));
        console.log("");
        console.log(renderFooter());
        console.log("");
      } else {
        if (isVerbose) {
          console.log(
            colors.dim(
              ` > Writing verbose output to console - as a result of the ${args["verbose"] ? 'user provided "verbose" option' : "EXAMPLES_CLI_VERBOSE environment variable"} `
            )
          );
          console.log("");

          if (isPromptEnabled) {
            console.log(colors.dim(" > Running in interactive mode..."));
          } else {
            console.log(colors.dim(" > Running in non-interactive mode..."));
          }
          console.log("");
        }

        if (args["script"] === undefined && process.env.EXAMPLES_CLI_SCRIPT) {
          args["script"] = process.env.EXAMPLES_CLI_SCRIPT;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the script option to ${process.env.EXAMPLES_CLI_SCRIPT} (via the EXAMPLES_CLI_SCRIPT environment variable) `
              )
            );
          }
        }

        if (args["config"] === undefined && process.env.EXAMPLES_CLI_CONFIG) {
          args["config"] = process.env.EXAMPLES_CLI_CONFIG;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the config option to ${process.env.EXAMPLES_CLI_CONFIG} (via the EXAMPLES_CLI_CONFIG environment variable) `
              )
            );
          }
        }

        if (args["script"] === undefined) {
          if (isPromptEnabled) {
            args["script"] = await prompt<string | true>(
              `Please select a Script value ${colors.gray("(The path to write the completion script to)")}`,
              {
                type: "select",
                options: ["string", "true"]
              }
            );
          }
        }

        if (args["config"] === undefined) {
          if (isPromptEnabled) {
            args["config"] = await prompt<string | true>(
              `Please select a Config value ${colors.gray("(The configuration file to append the completion script to)")}`,
              {
                type: "select",
                options: ["string", "true"]
              }
            );
          }
        }

        await handleCommand(deserialize<CompletionsBashPayload>(args));
      }
    }
  } catch (err) {
    console.error(
      ` ${colors.red("✘")} ${colors.white(`Error occurred while processing CLI Completions - Bash Shell command.`)}`
    );
  }
}

export default handler;
