/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { colors } from "../../../runtime/cli";

/**
 * Renders the CLI Completions - Bash Shell command usage information.
 *
 * @param mode - The render mode to use when displaying the usage information (either "full" or "minimal").
 * @returns The rendered string displaying usage information.
 */
export function renderUsage(mode: "full" | "minimal" = "full"): string {
  return `${colors.whiteBright(colors.bold(`CLI Completions - Bash Shell${mode === "minimal" ? " Command" : ""}`))}

  ${colors.gray("Generates a Bash shell completion script for the Examples CLI App CLI application.")}

  ${colors.whiteBright(colors.bold("Usage:"))}
    examples-cli completions bash [options] 

  ${colors.whiteBright(colors.bold("Options:"))}
    --help, -h, -?                       ${colors.gray("Show help information. [default: false]")} 
    --version, -v                        ${colors.gray("Show the version of the application. [default: false]")} 
    --interactive, -i, --interact        ${colors.gray("Enable interactive mode (will be set to false if running in a CI pipeline). [default: true]")} 
    --no-interactive, --no-interact      ${colors.gray("Disable interactive mode (will be set to true if running in a CI pipeline). [default: false]")} 
    --no-banner                          ${colors.gray("Hide the banner displayed while running the CLI application (will be set to true if running in a CI pipeline). [default: false]")} 
    --verbose, -v                        ${colors.gray("Enable verbose output. [default: false]")} 
    --script <script>, -s <script>       ${colors.gray("The path to write the completion script to. Valid options are: string, true")} 
    --config <config>, -c <config>       ${colors.gray("The configuration file to append the completion script to. Valid options are: string, true")}
`;
}
