/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import type {
StormBuildInfo,
StormRuntimeInfo
} from "@storm-stack/types/node";
import { isCI, isInteractive } from "@stryke/env/ci-checks";
import {
  hasTTY,
  isColorSupported,
  isDebug,
  isDevelopment,
  isLinux,
  isMacOS,
  isMinimal,
  isProduction,
  isStaging,
  isTest,
  isWindows,
  nodeMajorVersion,
  nodeVersion
} from "@stryke/env/environment-checks";
import {
  getEnvPaths as _getEnvPaths,
  EnvPaths
} from "@stryke/env/get-env-paths";
import { providerInfo } from "@stryke/env/providers";
import {
  runtimeInfo as baseRuntimeInfo,
  isBun,
  isDeno,
  isEdgeLight,
  isFastly,
  isNetlify,
  isNode,
  isWorkerd
} from "@stryke/env/runtime-checks";

/**
 * Get the build information for the current application.
 *
 * @returns The build information for the current application.
 */
export function getBuildInfo(): StormBuildInfo {
  return {
    name: $storm.vars.APP_NAME!,
    packageName: "@storm-stack/examples-cli-app",
    version: $storm.vars.APP_VERSION!,
    buildId: $storm.vars.BUILD_ID!,
    timestamp: $storm.vars.BUILD_TIMESTAMP
      ? Number($storm.vars.BUILD_TIMESTAMP)
      : 0,
    releaseId: $storm.vars.RELEASE_ID!,
    mode: ($storm.vars.MODE ||
      $storm.vars.NODE_ENV ||
      "production") as StormBuildInfo["mode"],
    platform: ($storm.vars.PLATFORM || "node") as StormBuildInfo["platform"],
    isTest,
    isDebug: isDebug || isDevelopment,
    isProduction,
    isStaging,
    isDevelopment
  };
}

let _envPaths!: EnvPaths;

/**
 * Get the environment paths for the current application.
 *
 * @returns The environment paths for the current application.
 */
export function getEnvPaths(): EnvPaths {
  if (!_envPaths) {
    _envPaths = _getEnvPaths({
      orgId: "storm-software",
      appId: "examples-cli-app"
    });
  }

  return _envPaths;
}

/**
 * Get the runtime information for the current application.
 *
 * @returns The runtime information for the current application.
 */
export function getRuntimeInfo(): StormRuntimeInfo {
  return {
    ...baseRuntimeInfo,
    isNode,
    isBun,
    isDeno,
    isFastly,
    isNetlify,
    isEdgeLight,
    isWorkerd,
    hasTTY,
    isWindows,
    isLinux,
    isMacOS,
    isCI: isCI(),
    isInteractive: isInteractive(),
    isMinimal,
    isColorSupported,
    isServer:
      isNode ||
      isDeno ||
      isBun ||
      isEdgeLight ||
      isFastly ||
      isNetlify ||
      isWorkerd,
    nodeVersion,
    nodeMajorVersion,
    provider: providerInfo
  };
}
