/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { createStorage } from "unstorage";
import fsLiteDriver from "unstorage/drivers/fs-lite";

export const storage = createStorage();
storage.mount(
  "logs",
  fsLiteDriver({
    base: "/home/development/.local/state/storm-software/storm-stack"
  })
);
