/* -------------------------------------------------------------------

                  ⚡ Storm Software - Storm Stack

 This code was released as part of the Storm Stack project. Storm Stack
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/storm-stack.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/storm-stack
 Documentation:            https://docs.stormsoftware.com/projects/storm-stack
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { ResolvedOptions } from "@storm-stack/core/types/build";
import { Context } from "@storm-stack/core/types/context";
import { PluginBaseOptions } from "@storm-stack/core/types/plugin";
import {
  EnvPluginOptions,
  EnvPluginResolvedOptions
} from "@storm-stack/plugin-env/types";

export interface ErrorPluginOptions extends PluginBaseOptions {
  /**
   * The path (relative to the workspace root) to the file that will be used to generate the errors map
   *
   * @remarks
   * This file will be generated by the Babel plugin (if it doesn't already exist) and will contain list of error codes/messages that can be thrown by the application.
   *
   * @defaultValue "tools/errors/codes.json"
   */
  codesFile?: string;

  /**
   * A URL to a page that looks up the workspace's error messages given a specific error code.
   */
  url?: string;

  /**
   * Options for the environment configuration plugin.
   */
  env?: EnvPluginOptions;
}

export interface ErrorPluginResolvedOptions {
  error: Required<Omit<ErrorPluginOptions, "env" | "url">> &
    Pick<ErrorPluginOptions, "url">;
  env: EnvPluginResolvedOptions["env"];
}

export type ErrorPluginContext = Context<
  ResolvedOptions<ErrorPluginResolvedOptions>
>;
