/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import handle from "../../../src/commands/serve";
import { ServePayload } from "../../../src/types";
import { withContext } from "../../runtime/app";
import { colors, prompt, renderBanner, renderFooter } from "../../runtime/cli";
import { getRuntimeInfo } from "../../runtime/env";

/**
 * Renders the Serve command usage information.
 *
 * @param includeCommands - Whether to include rendering sub-commands.
 * @returns The rendered string displaying usage information.
 */
export function renderUsage(includeCommands = true) {
  return `${colors.bold("Serve")}

${colors.dim("Start a server and serve the application.")}

  ${colors.bold("Usage:")}
    examples-cli serve [options] 

  ${colors.bold("Options:")}
    --help, -h, -?                   ${colors.dim("Show help information. [default: false]")} 
    --version, -v                    ${colors.dim("Show the version of the application. [default: false]")} 
    --interactive, -i, --interact    ${colors.dim("Enable interactive mode (will be set to false if running in a CI pipeline). [default: true]")} 
    --no-interactive, --no-interact  ${colors.dim("Disable interactive mode (will be set to true if running in a CI pipeline). [default: false]")} 
    --no-banner                      ${colors.dim("Hide the banner displayed while running the CLI application (will be set to true if running in a CI pipeline). [default: false]")} 
    --verbose, -v                    ${colors.dim("Enable verbose output. [default: false]")} 
    --host <host>                    ${colors.dim('The host to bind the server to. [default: "localhost"]')} 
    --port <port>, -p <port>         ${colors.dim("The port to bind the server to. [default: 3000]")} 
    --compress, -c                   ${colors.dim("Should the server serve compressed files.")} 
    --no-compress                    ${colors.dim("The inverse of the compress option. [default: false]")} 
    --platform <platform>            ${colors.dim('Should the server serve compressed files. Valid options are: node, browser [default: "node"]')} 
    --load-env, -l                   ${colors.dim("Should the server load environment variables from the .env file. [default: true]")} 
    --no-load-env                    ${colors.dim("The inverse of the load-env option. [default: false]")}
`;
}

const handleCommand = withContext<ServePayload>(handle);

/**
 * The entry point for the Serve command.
 */
async function handler() {
  try {
    const args = parseArgs(process.argv.slice(2), {
      boolean: [
        "help",
        "h",
        "?",
        "version",
        "v",
        "interactive",
        "i",
        "interact",
        "no-interactive",
        "no-interact",
        "no-banner",
        "",
        "verbose",
        "v",
        "compress",
        "c",
        "no-compress",
        "",
        "load-env",
        "l",
        "no-load-env",
        ""
      ],
      alias: {
        help: ["help", "HELP", "h", "H", "?", "?"],
        version: ["version", "VERSION", "v", "V"],
        interactive: [
          "interactive",
          "INTERACTIVE",
          "i",
          "I",
          "interact",
          "INTERACT"
        ],
        noInteractive: [
          "no-interactive",
          "NO-INTERACTIVE",
          "no-interact",
          "NO-INTERACT"
        ],
        noBanner: ["no-banner", "NO-BANNER"],
        verbose: ["verbose", "VERBOSE", "v", "V"],
        host: ["host", "HOST"],
        port: ["port", "PORT", "p", "P"],
        compress: ["compress", "COMPRESS", "c", "C"],
        noCompress: ["no-compress", "NO-COMPRESS"],
        platform: ["platform", "PLATFORM"],
        loadEnv: ["load-env", "LOAD-ENV", "l", "L"],
        noLoadEnv: ["no-load-env", "NO-LOAD-ENV"]
      }
    });

    if (args["version"] || args["v"]) {
      console.log($storm.vars.APP_VERSION);
    } else {
      const runtimeInfo = getRuntimeInfo();
      const isVerbose =
        args["verbose"] ?? Boolean(process.env.EXAMPLES_CLI_VERBOSE);
      const isInteractive =
        args["interactive"] !== false &&
        args["no-interactive"] !== true &&
        Boolean(process.env.EXAMPLES_CLI_INTERACTIVE) &&
        runtimeInfo.isInteractive &&
        !runtimeInfo.isCI;

      if (args["no-banner"] !== true && !runtimeInfo.isCI) {
        console.log(
          renderBanner("Serve", "Start a server and serve the application.")
        );
        console.log("");
      }

      if (args["help"] || args["h"] || args["?"]) {
        console.log(renderUsage(true));
        console.log("");
        console.log(renderFooter());
        console.log("");
      } else {
        if (isVerbose) {
          console.log(
            colors.dim(
              ` > Writing verbose output to console - as a result of the ${args["verbose"] ? 'user provided "verbose" option' : "EXAMPLES_CLI_VERBOSE environment variable"} `
            )
          );
          console.log("");

          if (isInteractive) {
            console.log(colors.dim(" > Running in interactive mode..."));
          } else {
            console.log(colors.dim(" > Running in non-interactive mode..."));
          }
          console.log("");
        }

        if (args["host"] === undefined && process.env.EXAMPLES_CLI_HOST) {
          args["host"] = process.env.EXAMPLES_CLI_HOST;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the host option to ${process.env.EXAMPLES_CLI_HOST} (via the EXAMPLES_CLI_HOST environment variable) `
              )
            );
          }
        }

        if (args["port"] === undefined && process.env.EXAMPLES_CLI_PORT) {
          args["port"] = process.env.EXAMPLES_CLI_PORT;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the port option to ${process.env.EXAMPLES_CLI_PORT} (via the EXAMPLES_CLI_PORT environment variable) `
              )
            );
          }
        }

        if (
          args["compress"] === undefined &&
          process.env.EXAMPLES_CLI_COMPRESS
        ) {
          args["compress"] = process.env.EXAMPLES_CLI_COMPRESS;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the compress option to ${process.env.EXAMPLES_CLI_COMPRESS} (via the EXAMPLES_CLI_COMPRESS environment variable) `
              )
            );
          }
        }

        if (
          args["no-compress"] === undefined &&
          process.env.EXAMPLES_CLI_NO_COMPRESS
        ) {
          args["no-compress"] = process.env.EXAMPLES_CLI_NO_COMPRESS;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the no-compress option to ${process.env.EXAMPLES_CLI_NO_COMPRESS} (via the EXAMPLES_CLI_NO_COMPRESS environment variable) `
              )
            );
          }
        }

        if (
          args["platform"] === undefined &&
          process.env.EXAMPLES_CLI_PLATFORM
        ) {
          args["platform"] = process.env.EXAMPLES_CLI_PLATFORM;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the platform option to ${process.env.EXAMPLES_CLI_PLATFORM} (via the EXAMPLES_CLI_PLATFORM environment variable) `
              )
            );
          }
        }

        if (
          args["load-env"] === undefined &&
          process.env.EXAMPLES_CLI_LOAD_ENV
        ) {
          args["load-env"] = process.env.EXAMPLES_CLI_LOAD_ENV;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the load-env option to ${process.env.EXAMPLES_CLI_LOAD_ENV} (via the EXAMPLES_CLI_LOAD_ENV environment variable) `
              )
            );
          }
        }

        if (
          args["no-load-env"] === undefined &&
          process.env.EXAMPLES_CLI_NO_LOAD_ENV
        ) {
          args["no-load-env"] = process.env.EXAMPLES_CLI_NO_LOAD_ENV;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the no-load-env option to ${process.env.EXAMPLES_CLI_NO_LOAD_ENV} (via the EXAMPLES_CLI_NO_LOAD_ENV environment variable) `
              )
            );
          }
        }

        if (args["host"] === undefined) {
          if (isInteractive) {
            args["host"] = await prompt<string>(
              "The host to bind the server to",
              {
                type: "text",
                initial: "localhost",
                default: "localhost"
              }
            );
          } else {
            args["host"] = "localhost";
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the host option to "localhost" (via it's default value) `
                )
              );
            }
          }
        }

        if (args["port"] === undefined) {
          if (isInteractive) {
            args["port"] = await prompt<number>(
              "The port to bind the server to",
              {
                type: "text",
                initial: "3000",
                default: "3000"
              }
            );
          } else {
            args["port"] = 3000;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the port option to 3000 (via it's default value) `
                )
              );
            }
          }
        }

        if (args["compress"] === undefined) {
          if (isInteractive) {
            args["compress"] = await prompt<boolean>(
              "Should the server serve compressed files",
              {
                type: "confirm"
              }
            );
          } else {
            args["compress"] = undefined;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the compress option to undefined (via it's default value) `
                )
              );
            }
          }
        }

        if (args["no-compress"] === undefined) {
          if (isInteractive) {
            args["no-compress"] = await prompt<boolean>(
              "The inverse of the compress option.",
              {
                type: "confirm",
                initial: false
              }
            );
          } else {
            args["no-compress"] = false;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the no-compress option to false (via it's default value) `
                )
              );
            }
          }
        }

        if (args["platform"] === undefined) {
          if (isInteractive) {
            args["platform"] = await prompt<"node" | "browser">(
              "Should the server serve compressed files",
              {
                type: "select",
                initial: "node",
                options: ["node", "browser"]
              }
            );
          } else {
            args["platform"] = "node";
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the platform option to "node" (via it's default value) `
                )
              );
            }
          }
        }

        if (args["load-env"] === undefined) {
          if (isInteractive) {
            args["load-env"] = await prompt<boolean>(
              "Should the server load environment variables from the .env file",
              {
                type: "confirm",
                initial: true
              }
            );
          } else {
            args["load-env"] = true;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the load-env option to true (via it's default value) `
                )
              );
            }
          }
        }

        if (args["no-load-env"] === undefined) {
          if (isInteractive) {
            args["no-load-env"] = await prompt<boolean>(
              "The inverse of the load-env option.",
              {
                type: "confirm",
                initial: false
              }
            );
          } else {
            args["no-load-env"] = false;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the no-load-env option to false (via it's default value) `
                )
              );
            }
          }
        }

        await handleCommand(deserialize<ServePayload>(args));
      }
    }
  } catch (err) {
    console.error(
      ` ${colors.red("✖")} ${colors.redBright(`Error occurred while processing Serve command.`)}`
    );
  }
}

export default handler;
