/* -------------------------------------------------------------------

                  ⚡ Storm Software - Storm Stack

 This code was released as part of the Storm Stack project. Storm Stack
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/storm-stack.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/storm-stack
 Documentation:            https://docs.stormsoftware.com/projects/storm-stack
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { Show } from "@alloy-js/core";
import { ComponentProps } from "../../types/templates";
import { SingleLineComment } from "./SingleLineComment";

export interface TypescriptFileHeaderProps extends ComponentProps {
  /**
   * If true, disables the ESLint directive at the top of the file.
   *
   * @defaultValue true
   */
  disableEslint?: boolean;

  /**
   * If true, disables the Biome directive at the top of the file.
   *
   * @defaultValue true
   */
  disableBiome?: boolean;

  /**
   * If true, disables the Prettier directive at the top of the file.
   *
   * @defaultValue false
   */
  disablePrettier?: boolean;
}

/**
 * Renders the header for a Storm Stack Typescript source file.
 *
 * @param props - The properties for the source file header.
 * @returns The rendered source file header.
 */
export function TypescriptFileHeader(props: TypescriptFileHeaderProps) {
  const {
    disableEslint = true,
    disableBiome = true,
    disablePrettier = false,
    children
  } = props;

  return (
    <>
      <Show when={!!disableEslint}>
        <SingleLineComment variant="slash-star">
          {"eslint-disable"}
        </SingleLineComment>
        <hbr />
      </Show>
      <Show when={!!disablePrettier}>
        <SingleLineComment variant="slash-star">
          {"prettier-ignore"}
        </SingleLineComment>
        <hbr />
      </Show>
      <Show when={!!disableBiome}>
        <SingleLineComment>{"biome-ignore lint: disable"}</SingleLineComment>
        <hbr />
      </Show>
      <Show when={!!children}>
        <>
          {children}
          <hbr />
        </>
      </Show>
      <SingleLineComment>{"Generated by Storm Stack"}</SingleLineComment>
      <SingleLineComment>
        {
          'NOTE: Do not edit this file manually - it will be overwritten automatically by the "storm prepare" command'
        }
      </SingleLineComment>
      <hbr />
    </>
  );
}
