/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

// Do nothing - this is a placeholder for Storm Stack plugins that do not require any initialization

export default function init() {
  // This function is intentionally left empty.
  // It serves as a placeholder for Storm Stack plugins that do not require any initialization.
}
