/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { createStorage } from "unstorage";
import storageCloudflareKvStorageStorage from "./storage/storage-cloudflare-kv-storage";

export const storage = createStorage();

storage.mount("storage", storageCloudflareKvStorageStorage);
