import type { ReactNode } from "react";
import "./global.css";

export const metadata = {
  title: "Welcome to docs-website",
  description: "Generated by create-nx-workspace"
};

export default function RootLayout({
  children
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
