
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface StormStackCloudflareAppBuildExecutorSchema {
 /**
  * Output Path
  * 
  * The output path for the build
  * 
  * @default "dist/{projectRoot}"
  * 
  * @format path
 */
 outputPath?: string,

 /**
  * TypeScript Configuration File
  * 
  * The path to the tsconfig file
  * 
  * @default "{projectRoot}/tsconfig.json"
  * 
  * @format path
 */
 tsconfig?: string,

 /**
  * Skip Installs
  * 
  * Skip installing dependencies during prepare stage
  * 
 */
 skipInstalls?: boolean,

 /**
  * Skip Cache
  * 
  * Skip the cache when building
  * 
 */
 skipCache?: boolean,

 /**
  * Silent
  * 
  * Should the build run silently - only report errors back to the user
  * 
  * @default false
 */
 silent?: boolean,

 /**
  * Entry File
  * 
  * The entry file or files to build
  * 
  * @default "{sourceRoot}/index.ts"
 */
 entry: string,

 /**
  * Mode
  * 
  * The build mode
  * 
  * @default "production"
  * 
  * @enum development,staging,production
 */
 mode?: string,
}

