/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize,serialize } from "@deepkit/type";
import { colors } from "../../../runtime/cli";
import { StormVariables } from "../../../runtime/env";
import { StormPayload } from "../../../runtime/payload";

export interface VarsDeletePayload {
  /**
   * The name of the variable to delete from the variables store.
   */
  name: string;
}

/**
 * Deletes a configuration parameter from the variables store.
 *
 * @param payload - The payload object containing the variable name to delete.
 */
async function handler(payload: StormPayload<VarsDeletePayload>) {
  const varsFile = await $storm.storage.getItem(`vars:vars.json`);
  if (varsFile === undefined) {
    console.error(
      ` ${colors.red("✘")} ${colors.redBright(`Variables file was not found`)}`
    );
    return;
  }

  const vars = deserialize<StormVariables>(varsFile);

  delete vars[payload.data.name];
  await $storm.storage.setItem(
    `vars:vars.json`,
    serialize<StormVariables>(vars)
  );

  console.log("");
  console.log(colors.dim(` > \`${payload.data.name}\` variable deleted`));
  console.log("");
}

export default handler;
