/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize,serialize } from "@deepkit/type";
import { colors } from "../../../runtime/cli";

export interface VarsDeletePayload {
  /**
   * The key to delete from the variables.
   */
  key: string;
}

/**
 * Deletes a configuration parameter from the variables store.
 *
 * @param payload - The payload object containing the variable key to delete.
 */
async function handler(payload: StormPayload<VarsDeletePayload>) {
  const varsFile = await $storm.storage.getItem(`vars:vars.json`);
  if (varsFile === undefined) {
    console.error(
      ` ${colors.red("✖")} ${colors.redBright(`Variables file was not found`)}`
    );
    return;
  }

  const vars = deserialize<StormVariables>(varsFile);

  delete vars[payload.data.key];
  await $storm.storage.setItem(`vars:vars.json`, serialize(vars));

  console.log("");
  console.log(colors.dim(" > \`${payload.data.key}\` variable deleted"));
  console.log("");
}

export default handler;
