/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import { withContext } from "../../../runtime/app";
import {
  colors,
  parseArgs,
  prompt,
  renderBanner,
  renderFooter
} from "../../../runtime/cli";
import { isInteractive, isMinimal } from "../../../runtime/env";
import handle from "./handle";
import { renderUsage } from "./usage";

export interface VarsDeletePayload {
  help: boolean;
  version: boolean;
  interactive: boolean;
  noInteractive: boolean;
  noBanner: boolean;
  verbose: boolean;
  name: string;
}

const handleCommand = withContext<VarsDeletePayload>(handle);

/**
 * The entry point for the Variables - Delete command.
 */
async function handler() {
  try {
    const args = parseArgs(process.argv.slice(4), {
      boolean: [
        "help",
        "h",
        "?",
        "version",
        "v",
        "interactive",
        "i",
        "interact",
        "no-interactive",
        "no-interact",
        "no-banner",
        "",
        "verbose",
        "v"
      ],
      alias: {
        help: ["help", "HELP", "h", "H", "?", "?"],
        version: ["version", "VERSION", "v", "V"],
        interactive: [
          "interactive",
          "INTERACTIVE",
          "i",
          "I",
          "interact",
          "INTERACT"
        ],
        noInteractive: [
          "no-interactive",
          "NO-INTERACTIVE",
          "no-interact",
          "NO-INTERACT"
        ],
        noBanner: ["no-banner", "NO-BANNER"],
        verbose: ["verbose", "VERBOSE", "v", "V"],
        name: ["name", "NAME", "n", "N"]
      }
    });

    if (args["version"] || args["v"]) {
      console.log($storm.vars.APP_VERSION);
    } else {
      const isVerbose =
        args["verbose"] ?? Boolean(process.env.EXAMPLES_CLI_VERBOSE);
      const isPromptEnabled =
        args["interactive"] !== false &&
        args["no-interactive"] !== true &&
        Boolean(process.env.EXAMPLES_CLI_INTERACTIVE) &&
        isInteractive &&
        !isMinimal;

      if (args["no-banner"] !== true && !isMinimal) {
        console.log(
          renderBanner(
            "Variables - Delete Command",
            "Deletes a configuration parameter from the variables store."
          )
        );
        console.log("");
      }

      if (args["help"] || args["h"] || args["?"]) {
        console.log(renderUsage("full"));
        console.log("");
        console.log(renderFooter());
        console.log("");
      } else {
        if (isVerbose) {
          console.log(
            colors.dim(
              ` > Writing verbose output to console - as a result of the ${args["verbose"] ? 'user provided "verbose" option' : "EXAMPLES_CLI_VERBOSE environment variable"} `
            )
          );
          console.log("");

          if (isPromptEnabled) {
            console.log(colors.dim(" > Running in interactive mode..."));
          } else {
            console.log(colors.dim(" > Running in non-interactive mode..."));
          }
          console.log("");
        }

        if (args["name"] === undefined && process.env.EXAMPLES_CLI_NAME) {
          args["name"] = process.env.EXAMPLES_CLI_NAME;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the name option to ${process.env.EXAMPLES_CLI_NAME} (via the EXAMPLES_CLI_NAME environment variable) `
              )
            );
          }
        }

        if (args["name"] === undefined) {
          if (isPromptEnabled) {
            args["name"] = await prompt<string>(`Please provide a Name`, {
              type: "text",
              placeholder:
                "The name of the variable to delete from the variables store"
            });
          }
        }

        await handleCommand(deserialize<VarsDeletePayload>(args));
      }
    }
  } catch (err) {
    console.error(
      ` ${colors.red("✘")} ${colors.redBright(`Error occurred while processing Variables - Delete command.`)}`
    );
  }
}

export default handler;
