#!/usr/bin/env node

/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { isError } from "@stryke/type-checks/is-error";
import handleAdd, { renderUsage as renderAddUsage } from "./commands/add";
import { colors } from "./runtime/cli";

async function main() {
  try {
    if (process.argv.includes("--version") || process.argv.includes("-v")) {
      console.log($storm.vars.APP_VERSION);
    } else {
      let command = "";
      if (process.argv.length > 2 && process.argv[2]) {
        command = process.argv[2];
      }

      if (command.toLowerCase() === "add") {
        return handleAdd();
      } else if (command.toLowerCase() === "add") {
        return handleAdd();
      } else {
        console.error(colors.red(`Unknown command: ${colors.bold(command)}`));
      }

      console.log("");
      console.log(
        "The following commands are available as part of the examples-cli-app application:"
      );
      console.log("");
      console.log(renderAddUsage());
      console.log(renderAddUsage());
      console.log("");
    }
  } catch (err) {
    if (isError(err)) {
      console.error(
        colors.red(`Error occurred while processing command: ${err.message}`)
      );
    } else {
      console.error(colors.red(`Unknown error occurred: ${err}`));
    }
  }
}

await main();
