/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import "./runtime/init";

import { getSink as getStorageSink } from "@storm-stack/log-storage";
import { createStorage } from "unstorage";
import fsLiteDriver from "unstorage/drivers/fs-lite";
import handle from "../src/commands/serve";
import { builder } from "./runtime/app";

const storage = createStorage();
storage.mount("logs", fsLiteDriver({ base: "var/log" }));

export default builder({
  name: "examples-cli-app",
  log: [{ handle: await getStorageSink({ storage }), logLevel: "debug" }],
  storage
})
  .handler(handle)
  .build();
