/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { join } from "node:path";
import fsLiteDriver from "unstorage/drivers/fs-lite";
import { paths } from "../env";

export default fsLiteDriver({
  base: join(paths.log, "crash-reports"),
  readOnly: false,
  noClear: false
});
