/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import type {
StormBuildInfo,
StormContext,
StormRuntimeInfo
} from "@storm-stack/plugin-node/types";
import { isCI, isInteractive } from "@stryke/env/ci-checks";
import {
  hasTTY,
  isColorSupported,
  isDebug,
  isDevelopment,
  isLinux,
  isMacOS,
  isMinimal,
  isProduction,
  isStaging,
  isTest,
  isWindows,
  nodeMajorVersion,
  nodeVersion
} from "@stryke/env/environment-checks";
import { getEnvPaths } from "@stryke/env/get-env-paths";
import { providerInfo } from "@stryke/env/providers";
import {
  runtimeInfo as baseRuntimeInfo,
  isBun,
  isDeno,
  isEdgeLight,
  isFastly,
  isNetlify,
  isNode,
  isWorkerd
} from "@stryke/env/runtime-checks";
import { AsyncLocalStorage } from "node:async_hooks";
import { getContext } from "unctx";
import { StormError } from "./error";

const STORM_CONTEXT_KEY = "storm-stack";

export const STORM_ASYNC_CONTEXT = getContext<StormContext>(STORM_CONTEXT_KEY, {
  asyncContext: true,
  AsyncLocalStorage
});

export const getBuildInfo = (): StormBuildInfo => {
  return {
    name: $storm.env.APP_NAME!,
    version: $storm.env.APP_VERSION!,
    buildId: $storm.env.BUILD_ID!,
    timestamp: $storm.env.BUILD_TIMESTAMP
      ? Number($storm.env.BUILD_TIMESTAMP)
      : 0,
    releaseId: $storm.env.RELEASE_ID!,
    mode: ($storm.env.MODE ||
      $storm.env.NODE_ENV ||
      "production") as StormBuildInfo["mode"],
    platform: ($storm.env.PLATFORM || "node") as StormBuildInfo["platform"],
    isTest,
    isDebug: isDebug || isDevelopment,
    isProduction,
    isStaging,
    isDevelopment
  };
};

export const envPaths = getEnvPaths({
  orgId: "storm-software",
  appId: "examples-node-app"
});

export const getRuntimeInfo = (): StormRuntimeInfo => {
  return {
    ...baseRuntimeInfo,
    isNode,
    isBun,
    isDeno,
    isFastly,
    isNetlify,
    isEdgeLight,
    isWorkerd,
    hasTTY,
    isWindows,
    isLinux,
    isMacOS,
    isCI: isCI(),
    isInteractive: isInteractive(),
    isMinimal,
    isColorSupported,
    isServer:
      isNode ||
      isDeno ||
      isBun ||
      isEdgeLight ||
      isFastly ||
      isNetlify ||
      isWorkerd,
    nodeVersion,
    nodeMajorVersion,
    provider: providerInfo
  };
};

export function useStorm(): StormContext {
  try {
    return STORM_ASYNC_CONTEXT.use();
  } catch {
    throw new StormError({ type: "general", code: 12 });
  }
}
