/* eslint-disable */
// biome-ignore lint: disable

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

type ErrorMessageDetails = MessageDetails<"error">;

/**
 * The type of error response message/event
 */
type ErrorType =
  | "general"
  | "not_found"
  | "validation"
  | "service_unavailable"
  | "action_unsupported"
  | "security"
  | "unknown";

/**
 * The formatted values for a log record.
 */
interface FormattedValues {
  /**
   * The formatted timestamp.
   */
  timestamp: string;
  /**
   * The formatted log level.
   */
  level: string;
  /**
   * The formatted message.
   */
  message: string;
  /**
   * The unformatted log record.
   */
  record: LogRecord;
}

type HandlerFunction<TInput = any, TOutput = any> = (
  payload: IStormPayload<TInput>
) => MaybePromise<TOutput | IStormError>;

type HelpMessageDetails = MessageDetails<"help">;

type InfoMessageDetails = MessageDetails<"info">;

/**
 * A store that exists on the StormContext for internal use.
 *
 * @remarks
 * Please do not use this in application code as it is likely to change
 *
 * @internal
 */
declare interface Internal_StormContextStore {
  /**
   * List of events that have been emitted
   *
   * @internal
   */
  events: IStormEvent[];
}

/**
 * The Storm Error interface.
 */
interface IStormError extends Error {
  /**
   * The error code
   */
  code: number;
  /**
   * The error message parameters
   */
  params: string[];
  /**
   * The type of error that was thrown.
   */
  type: ErrorType;
  /**
   * A url to display the error message
   */
  url: string;
  /**
   * Additional data to be passed with the error
   */
  data?: any;
  /**
   * The underlying cause of the error, if any. This is typically another error object that caused this error to be thrown.
   */
  cause: IStormError | undefined;
  /**
   * The error stack
   *
   * @remarks
   * This is overridden in `StormError` to be a parsed stacktrace
   */
  stack: string;
  /**
   * The parsed stacktrace
   */
  stacktrace: ParsedStacktrace[];
  /**
   * The original stacktrace
   */
  originalStack: string;
  /**
   * Returns a formatted error string that can be displayed to the user.
   */
  toDisplay: () => string;
  /**
   * Internal function to inherit the error
   *
   * @internal
   */
  __proto__: any;
}

interface IStormEvent<TEventType extends string = string, TData = any>
  extends IStormPayload<TData> {
  /**
   * The unique identifier for the payload.
   */
  payloadId: string;
  /**
   * The type of the event.
   */
  type: TEventType;
  /**
   * The version of the event.
   */
  version: string;
  /**
   * The event label.
   *
   * @remarks
   * The label format is "\{type\}-v\{version\}"
   */
  label: string;
}

/**
 * A logger interface. It provides methods to log messages at different severity levels.
 *
 * @remarks
 * The inspiration and much of the original implementation for this logger was taken from the [LogTape](https://logtape.org/) project. Major thanks to that project.
 *
 * ```typescript
 * $storm.log.debug(`A debug message with ${value}.`);
 * $storm.log.info(`An info message with ${value}.`);
 * $storm.log.warn(`A warning message with ${value}.`);
 * $storm.log.error(`An error message with ${value}.`);
 * $storm.log.fatal(`A fatal error message with ${value}.`);
 * ```
 */
interface IStormLog {
  /**
   * Get a logger with contextual properties. This is useful for log multiple messages with the shared set of properties.
   *
   * ```typescript
   * const ctx = $storm.log.with({ foo: 123, bar: "abc" });
   * ctx.info("A message with {foo} and {bar}.");
   * ctx.warn("Another message with {foo}, {bar}, and {baz}.", { baz: true });
   * ```
   *
   * The above code is equivalent to:
   *
   * ```typescript
   * $storm.log.info("A message with {foo} and {bar}.", { foo: 123, bar: "abc" });
   * $storm.log.warn(
   *   "Another message with {foo}, {bar}, and {baz}.",
   *   { foo: 123, bar: "abc", baz: true },
   * );
   * ```
   *
   * @param properties - The properties to add to the logger.
   * @returns A logger with the specified properties.
   */
  with: (properties: Record<string, unknown>) => IStormLog;
  /**
   * Log a debug message. Use this as a template string prefix.
   *
   * ```typescript
   * $storm.log.debug(`A debug message with ${value}.`);
   * ```
   *
   * @param message - The message template strings array.
   * @param values - The message template values.
   */
  debug: ((
    message: TemplateStringsArray,
    ...values: readonly unknown[]
  ) => void) &
    ((
      message: string,
      properties?: Record<string, unknown> | (() => Record<string, unknown>)
    ) => void) &
    ((callback: LogCallback) => void);
  /**
   * Log an informational message. Use this as a template string prefix.
   *
   * ```typescript
   * $storm.log.info(`An info message with ${value}.`);
   * ```
   *
   * @param message - The message template strings array.
   * @param values - The message template values.
   */
  info: ((
    message: TemplateStringsArray,
    ...values: readonly unknown[]
  ) => void) &
    ((
      message: string,
      properties?: Record<string, unknown> | (() => Record<string, unknown>)
    ) => void) &
    ((callback: LogCallback) => void);
  /**
   * Log a warning message. Use this as a template string prefix.
   *
   * ```typescript
   * $storm.log.warn(`A warning message with ${value}.`);
   * ```
   *
   * @param message - The message template strings array.
   * @param values - The message template values.
   */
  warn: ((
    message: TemplateStringsArray,
    ...values: readonly unknown[]
  ) => void) &
    ((
      message: string,
      properties?: Record<string, unknown> | (() => Record<string, unknown>)
    ) => void) &
    ((callback: LogCallback) => void);
  /**
   * Log an error message. Use this as a template string prefix.
   *
   * ```typescript
   * $storm.log.error(`An error message with ${value}.`);
   * ```
   *
   * @param message - The message template strings array.
   * @param values - The message template values.
   */
  error: ((
    message: TemplateStringsArray | Error,
    ...values: readonly unknown[]
  ) => void) &
    ((
      message: string,
      properties?: Record<string, unknown> | (() => Record<string, unknown>)
    ) => void) &
    ((callback: LogCallback) => void);
  /**
   * Log a fatal error message. Use this as a template string prefix.
   *
   * ```typescript
   * $storm.log.fatal(`A fatal error message with ${value}.`);
   * ```
   *
   * @param message - The message template strings array.
   * @param values - The message template values.
   */
  fatal: ((
    message: TemplateStringsArray | Error,
    ...values: readonly unknown[]
  ) => void) &
    ((
      message: string,
      properties?: Record<string, unknown> | (() => Record<string, unknown>)
    ) => void) &
    ((callback: LogCallback) => void);
}

interface IStormPayload<TData = any> {
  /**
   * The timestamp of the payload.
   */
  timestamp: number;
  /**
   * The unique identifier for the payload.
   */
  id: string;
  /**
   * The data of the payload.
   */
  data: TData;
}

/**
 * A Storm result interface. It represents the structure of a result returned by the Storm Stack runtime.
 *
 * @remarks
 * The `IStormResult` interface is used to standardize the structure of results returned by the Storm Stack runtime.
 * It includes properties for the request ID, data, error information, timestamp, and success status.
 */
interface IStormResult<TData extends any | IStormError = any | IStormError> {
  /**
   * The unique identifier for the payload.
   */
  payloadId: string;
  /**
   * The result meta.
   */
  meta: Record<string, any>;
  /**
   * The data of the result.
   */
  data: TData;
  /**
   * The timestamp of the result.
   */
  timestamp: number;
  /**
   * An indicator of whether the result was successful.
   */
  success: boolean;
}

/**
 * A logging callback function.  It is used to defer the computation of a
 * message template until it is actually logged.
 * @param prefix - The message template prefix.
 * @returns The rendered message array.
 */
type LogCallback = (prefix: LogTemplatePrefix) => unknown[];

/**
 * A filter is a function that accepts a log record and returns `true` if the
 * record should be passed to the sink.
 *
 * @param record - The log record to filter.
 * @returns `true` if the record should be passed to the sink.
 */
type LogFilter = (record: LogRecord) => boolean;

/**
 * A filter-like value is either a {@link LogFilter} or a {@link LogLevel}.
 * `null` is also allowed to represent a filter that rejects all records.
 */
type LogFilterLike = LogFilter | LogLevel | null;

/**
 * The severity level of a {@link LogRecord}.
 */
type LogLevel = "debug" | "info" | "warning" | "error" | "fatal";

const LogLevel: {
  DEBUG: LogLevel;
  INFO: LogLevel;
  WARNING: LogLevel;
  ERROR: LogLevel;
  FATAL: LogLevel;
};

/**
 * A log record.
 */
interface LogRecord {
  /**
   * The log level.
   */
  readonly level: LogLevel;
  /**
   * The log message.  This is the result of substituting the message template
   * with the values.  The number of elements in this array is always odd,
   * with the message template values interleaved between the substitution
   * values.
   */
  readonly message: readonly unknown[];
  /**
   * The raw log message. This is the original message template without any further processing. It can be either:
   * - A string without any substitutions if the log record was created with a method call syntax, e.g., "Hello, \{name\}!" for logger.info("Hello, \{name\}!", \{ name \}).
   * - A template string array if the log record was created with a tagged template literal syntax, e.g., ["Hello, ", "!"] for logger.info\`Hello, $\{name\}!\`
   */
  readonly rawMessage: string | TemplateStringsArray;
  /**
   * The timestamp of the log record in milliseconds since the Unix epoch.
   */
  readonly timestamp: number;
  /**
   * The extra properties of the log record.
   */
  readonly properties: Record<string, unknown>;
}

/**
 * A sink is a function that accepts a log record and prints it somewhere.
 *
 * @param record - The log record to sink.
 */
type LogSink = (record: LogRecord) => void;

interface LogSinkInstance {
  /**
   * The log sink function.
   */
  handle: LogSink;
  /**
   * The lowest log level for the sink to accept.
   */
  logLevel: LogLevel;
}

/**
 * A logging template prefix function.  It is used to log a message in
 * a {@link LogCallback} function.
 * @param message - The message template strings array.
 * @param values - The message template values.
 * @returns The rendered message array.
 */
type LogTemplatePrefix = (
  message: TemplateStringsArray,
  ...values: unknown[]
) => unknown[];

declare type MaybePromise<T> = T | Promise<T>;

type MessageDetails<TMessageType extends MessageType = MessageType> =
  | {
      code: string;
      message?: string;
      type: TMessageType;
      params?: Record<string, any>;
    }
  | {
      code?: string;
      message: string;
      type: TMessageType;
      params?: Record<string, any>;
    };

type MessageType = "help" | "error" | "warning" | "info" | "success";

interface ParsedStacktrace {
  column?: number;
  function?: string;
  line?: number;
  source: string;
}

type PostprocessFunction<
  TPayload extends IStormPayload,
  TContext extends StormContext<StormBaseVariables, any, TPayload>,
  TOutput
> = (
  context: TContext,
  output: TOutput
) => MaybePromise<IStormError | void | null | undefined>;

type PreprocessFunction<
  TPayload extends IStormPayload,
  TContext extends StormContext<StormBaseVariables, any, TPayload>
> = (context: TContext) => MaybePromise<IStormError | void | null | undefined>;

type SetupFunction = () => MaybePromise<IStormError | void | null | undefined>;

/**
 * The base variables used by Storm Stack applications
 *
 * @remarks
 * This interface is used to define the environment variables, configuration options, and runtime settings used by the Storm Stack applications. It is used to provide type safety, autocompletion, and default values for the environment variables. The comments of each variable are used to provide documentation descriptions when running the \`storm docs\` command.
 *
 * @categoryDescription Platform
 * The name of the platform the variable is intended for use in.
 *
 * @showCategories
 */
interface StormBaseVariables {
  /**
   * An indicator that specifies the application is running in the local Storm Stack development environment.
   *
   * @defaultValue false
   *
   * @hidden
   * @category node
   * @readonly
   */
  STORM_STACK_LOCAL: boolean;
  /**
   * The name of the application.
   *
   * @readonly
   * @category neutral
   */
  APP_NAME: string;
  /**
   * The version of the application.
   *
   * @defaultValue "1.0.0"
   *
   * @readonly
   * @category neutral
   */
  APP_VERSION: string;
  /**
   * The unique identifier for the build.
   *
   * @readonly
   * @category neutral
   */
  BUILD_ID: string;
  /**
   * The timestamp the build was ran at.
   *
   * @readonly
   * @category neutral
   */
  BUILD_TIMESTAMP: number;
  /**
   * A checksum hash created during the build.
   *
   * @readonly
   * @category neutral
   */
  BUILD_CHECKSUM: string;
  /**
   * The unique identifier for the release.
   *
   * @readonly
   * @category neutral
   */
  RELEASE_ID: string;
  /**
   * The tag for the release. This is generally in the format of "\<APP_NAME\>\@\<APP_VERSION\>".
   *
   * @readonly
   * @category neutral
   */
  RELEASE_TAG: string;
  /**
   * The name of the organization that maintains the application.
   *
   * @remarks
   * This variable is used to specify the name of the organization that maintains the application. If not provided in an environment, it will try to use the value in {@link @storm-software/config-tools/StormWorkspaceConfig#organization}.
   *
   * @alias ORG
   * @alias ORG_ID
   * @category neutral
   */
  ORGANIZATION: string;
  /**
   * The platform for which the application was built.
   *
   * @defaultValue "node"
   *
   * @category neutral
   */
  PLATFORM: "node" | "browser";
  /**
   * The mode in which the application is running.
   *
   * @defaultValue "production"
   *
   * @category neutral
   */
  MODE: "development" | "staging" | "production";
  /**
   * The environment the application is running in. This value will be populated with the value of `MODE` if not provided.
   *
   * @defaultValue "production"
   *
   * @alias ENV
   * @alias NODE_ENV
   * @alias VERCEL_ENV
   * @category neutral
   */
  ENVIRONMENT: string;
  /**
   * Indicates if the application is running in debug mode.
   *
   * @defaultValue false
   *
   * @category neutral
   */
  DEBUG: boolean;
  /**
   * An indicator that specifies the current runtime is a test environment.
   *
   * @defaultValue false
   *
   * @category neutral
   */
  TEST: boolean;
  /**
   * An indicator that specifies the current runtime is a minimal environment.
   *
   * @defaultValue false
   *
   * @category node
   */
  MINIMAL: boolean;
  /**
   * An indicator that specifies the current runtime is a no color environment.
   *
   * @defaultValue false
   *
   * @category node
   */
  NO_COLOR: boolean;
  /**
   * An indicator that specifies the current runtime is a force color environment.
   *
   * @defaultValue false
   *
   * @category node
   */
  FORCE_COLOR: boolean;
  /**
   * An indicator that specifies the current runtime should force hyperlinks in terminal output.
   *
   * @remarks
   * This variable is used to force hyperlinks in terminal output, even if the terminal does not support them. This is useful for debugging and development purposes.
   *
   * @defaultValue false
   *
   * @category node
   */
  FORCE_HYPERLINK: boolean;
  /**
   * The terminal type. This variable is set by certain CI/CD systems.
   *
   * @remarks
   * This variable is used to specify the terminal type that the application is running in. It can be used to determine how to format output for the terminal.
   *
   * @category node
   * @readonly
   */
  TERM?: string;
  /**
   * The terminal program name. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  TERM_PROGRAM: string;
  /**
   * The terminal program version. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  TERM_PROGRAM_VERSION: string;
  /**
   * The terminal emulator name. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  TERMINAL_EMULATOR?: string;
  /**
   * The terminal emulator session ID. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  WT_SESSION?: string;
  /**
   * An indicator that specifies the current terminal is running Terminus Sublime. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  TERMINUS_SUBLIME?: boolean;
  /**
   * The ConEmu task name. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  ConEmuTask?: string;
  /**
   * The cursor trace ID. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  CURSOR_TRACE_ID?: string;
  /**
   * The VTE version. This variable is set by certain terminal emulators.
   *
   * @category node
   * @readonly
   */
  VTE_VERSION?: string;
  /**
   * Indicates if error stack traces should be captured.
   *
   * @defaultValue false
   *
   * @category neutral
   */
  STACKTRACE: boolean;
  /**
   * Indicates if error data should be included.
   *
   * @defaultValue false
   *
   * @category neutral
   */
  INCLUDE_ERROR_DATA: boolean;
  /**
   * A web page to lookup error messages and display additional information given an error code.
   *
   * @remarks
   * This variable is used to provide a URL to a page that can be used to look up error messages given an error code. This is used to provide a more user-friendly error message to the user.
   *
   * @title Error Details URL
   * @category neutral
   */
  ERROR_URL: string;
  /**
   * The default timezone for the application.
   *
   * @defaultValue "America/New_York"
   *
   * @category neutral
   */
  DEFAULT_TIMEZONE: string;
  /**
   * The default locale for the application.
   *
   * @defaultValue "en_US"
   *
   * @category neutral
   */
  DEFAULT_LOCALE: string;
  /**
   * The default lowest log level to accept. If `null`, the logger will reject all records. This value only applies if `lowestLogLevel` is not provided to the `logs` configuration.
   *
   * @defaultValue "info"
   *
   * @category neutral
   */
  LOG_LEVEL?: LogLevel | null;
  /**
   * An indicator that specifies the current runtime is a continuous integration environment.
   *
   * @defaultValue false
   *
   * @title Continuous Integration
   * @alias CONTINUOUS_INTEGRATION
   * @category neutral
   */
  CI: boolean;
  /**
   * The unique identifier for the current run. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  RUN_ID?: string;
  /**
   * The agola git reference. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  AGOLA_GIT_REF?: string;
  /**
   * The appcircle build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  AC_APPCIRCLE?: string;
  /**
   * The appveyor build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  APPVEYOR?: string;
  /**
   * The codebuild build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CODEBUILD?: string;
  /**
   * The task force build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  TF_BUILD?: string;
  /**
   * The bamboo plan key. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  bamboo_planKey?: string;
  /**
   * The bitbucket commit. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  BITBUCKET_COMMIT?: string;
  /**
   * The bitrise build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  BITRISE_IO?: string;
  /**
   * The buddy workspace ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  BUDDY_WORKSPACE_ID?: string;
  /**
   * The buildkite build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  BUILDKITE?: string;
  /**
   * The circleci build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CIRCLECI?: string;
  /**
   * The cirrus-ci build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CIRRUS_CI?: string;
  /**
   * The cf build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CF_BUILD_ID?: string;
  /**
   * The cm build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CM_BUILD_ID?: string;
  /**
   * The ci name. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CI_NAME?: string;
  /**
   * The drone build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  DRONE?: string;
  /**
   * The dsari build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  DSARI?: string;
  /**
   * The earthly build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  EARTHLY_CI?: string;
  /**
   * The eas build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  EAS_BUILD?: string;
  /**
   * The gerrit project. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  GERRIT_PROJECT?: string;
  /**
   * The gitea actions build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  GITEA_ACTIONS?: string;
  /**
   * The github actions build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  GITHUB_ACTIONS?: string;
  /**
   * The gitlab ci build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  GITLAB_CI?: string;
  /**
   * The go cd build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  GOCD?: string;
  /**
   * The builder output build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  BUILDER_OUTPUT?: string;
  /**
   * The harness build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  HARNESS_BUILD_ID?: string;
  /**
   * The jenkins url. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  JENKINS_URL?: string;
  /**
   * The layerci build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  LAYERCI?: string;
  /**
   * The magnum build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  MAGNUM?: string;
  /**
   * The netlify build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  NETLIFY?: string;
  /**
   * The nevercode build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  NEVERCODE?: string;
  /**
   * The prow job ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  PROW_JOB_ID?: string;
  /**
   * The release build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  RELEASE_BUILD_ID?: string;
  /**
   * The render build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  RENDER?: string;
  /**
   * The sailci build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  SAILCI?: string;
  /**
   * The hudson build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  HUDSON?: string;
  /**
   * The screwdriver build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  SCREWDRIVER?: string;
  /**
   * The semaphore build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  SEMAPHORE?: string;
  /**
   * The sourcehut build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  SOURCEHUT?: string;
  /**
   * The strider build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  STRIDER?: string;
  /**
   * The task ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  TASK_ID?: string;
  /**
   * The teamcity version. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  TEAMCITY_VERSION?: string;
  /**
   * The travis build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  TRAVIS?: string;
  /**
   * The vela build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  VELA?: string;
  /**
   * The now builder build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  NOW_BUILDER?: string;
  /**
   * The appcenter build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  APPCENTER_BUILD_ID?: string;
  /**
   * The xcode project build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  CI_XCODE_PROJECT?: string;
  /**
   * The xcode server build ID. This value is set by certain CI/CD systems.
   *
   * @category node
   * @readonly
   */
  XCS?: string;
  /**
   * The Storm Stack application's runtime data directory.
   *
   * @remarks
   * This variable is used to override the base path of the system's local application data directory. This variable is used to set the \`$storm.paths.data\` property.
   *
   * @title Data Directory
   * @category node
   */
  DATA_DIR?: string;
  /**
   * The Storm Stack application's configuration data directory.
   *
   * @remarks
   * This variable is used to override the base path of the system's local application configuration directory. This variable is used to set the \`$storm.paths.config\` property.
   *
   * @title Configuration Directory
   * @category node
   */
  CONFIG_DIR?: string;
  /**
   * The Storm Stack application's cached data directory.
   *
   * @remarks
   * This variable is used to override the base path of the system's local cache data directory. This variable is used to set the \`$storm.paths.cache\` property.
   *
   * @title Cache Directory
   * @category node
   */
  CACHE_DIR?: string;
  /**
   * The Storm Stack application's logging directory.
   *
   * @remarks
   * This variable is used to override the base path of the system's local application log directory. This variable is used to set the \`$storm.paths.log\` property.
   *
   * @title Log Directory
   * @category node
   */
  LOG_DIR?: string;
  /**
   * The Storm Stack application's temporary data directory.
   *
   * @remarks
   * This variable is used to override the base path of the system's local temporary data directory. This variable is used to set the \`$storm.paths.temp\` property.
   *
   * @title Temporary Directory
   * @category node
   */
  TEMP_DIR?: string;
  /**
   * A variable that specifies the current user's local application data directory on Windows.
   *
   * @see https://www.advancedinstaller.com/appdata-localappdata-programdata.html
   *
   * @remarks
   * This variable is used to specify a path to application data that is specific to the current user. This variable can be used to set the \`$storm.paths.data\`, \`$storm.paths.cache\`, and \`$storm.paths.log\` properties.
   *
   * @category node
   * @readonly
   */
  LOCALAPPDATA?: string;
  /**
   * A variable that specifies the application data directory on Windows.
   *
   * @see https://www.advancedinstaller.com/appdata-localappdata-programdata.html
   *
   * @remarks
   * This variable is used to specify a path to application data that is specific to the current user. This variable can be used to set the \`$storm.paths.config\` property.
   *
   * @category node
   * @readonly
   */
  APPDATA?: string;
  /**
   * A variable that specifies the data path in the home directory on Linux systems using the XDG base directory specification.
   *
   * @see https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
   *
   * @remarks
   * This variable is used to specify a path to application data that is specific to the current user. This variable can be used to set the \`$storm.paths.data\` property.
   *
   * @category node
   * @readonly
   */
  XDG_DATA_HOME?: string;
  /**
   * A variable that specifies the configuration path in the home directory on Linux systems using the XDG base directory specification.
   *
   * @see https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
   *
   * @remarks
   * This variable is used to specify a path to configuration data that is specific to the current user. This variable can be used to set the \`$storm.paths.config\` property.
   *
   * @category node
   * @readonly
   */
  XDG_CONFIG_HOME?: string;
  /**
   * A variable that specifies the cache path in the home directory on Linux systems using the XDG base directory specification.
   *
   * @see https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
   *
   * @remarks
   * This variable is used to specify a path to cache data that is specific to the current user. This variable can be used to set the \`$storm.paths.cache\` property.
   *
   * @category node
   * @readonly
   */
  XDG_CACHE_HOME?: string;
  /**
   * A variable that specifies the state directory on Linux systems using the XDG base directory specification.
   *
   * @see https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
   *
   * @remarks
   * This variable is used to specify a path to application state data that is specific to the current user. This variable can be used to set the \`$storm.paths.state\` property.
   *
   * @category node
   * @readonly
   */
  XDG_STATE_HOME?: string;
  /**
   * A variable that specifies the runtime directory on Linux systems using the XDG base directory specification.
   *
   * @see https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
   *
   * @remarks
   * This variable is used to specify a path to runtime data that is specific to the current user. This variable can be used to set the \`$storm.paths.temp\` property.
   *
   * @category node
   * @readonly
   */
  XDG_RUNTIME_DIR?: string;
  /**
   * A variable that specifies the [Devenv](https://devenv.sh/) runtime directory.
   *
   * @see https://devenv.sh/files-and-variables/#devenv_dotfile
   * @see https://nixos.org/
   *
   * @remarks
   * This variable is used to specify a path to application data that is specific to the current [Nix](https://nixos.org/) environment. This variable can be used to set the \`$storm.paths.temp\` property.
   *
   * @category node
   */
  DEVENV_RUNTIME?: string;
}

/**
 * Interface representing the static build information for the Storm application.
 */
interface StormBuildInfo {
  /**
   * The package name of the application.
   */
  packageName: string;
  /**
   * The version of the application.
   */
  version: string;
  /**
   * The unique identifier for the build.
   */
  buildId: string;
  /**
   * The timestamp for the build.
   */
  timestamp: number;
  /**
   * The unique identifier for the release.
   */
  releaseId: string;
  /**
   * The tag associated with the release.
   *
   * @remarks
   * This is in the format of "\<APP_NAME\>\@\<APP_VERSION\>".
   */
  releaseTag: string;
  /**
   * The name of the organization that maintains the application.
   */
  organization: string;
  /**
   * The mode in which the application is running (e.g., 'development', 'staging', 'production').
   */
  mode: "development" | "staging" | "production";
  /**
   * The platform for which the application was built.
   */
  platform: "node" | "browser" | "neutral";
  /**
   * Indicates if the application is running in a production environment.
   */
  isProduction: boolean;
  /**
   * Indicates if the application is running in a staging environment.
   */
  isStaging: boolean;
  /**
   * Indicates if the application is running in a development environment.
   */
  isDevelopment: boolean;
}

/**
 * The global Storm Stack application context. This object contains information related to the current process's execution.
 *
 * @remarks
 * The Storm Stack application context object is injected into the global scope of the application. It can be accessed using `$storm` or `useStorm()` in the application code.
 */
type StormContext<
  TVars extends StormBaseVariables = StormBaseVariables,
  TAdditionalFields extends Record<string, any> = Record<string, any>,
  TPayload extends IStormPayload = IStormPayload
> = TAdditionalFields & {
  /**
   * The name of the Storm application.
   */
  readonly name: string;
  /**
   * The version of the Storm application.
   */
  readonly version: string;
  /**
   * The variables for the Storm application.
   */
  readonly vars: TVars;
  /**
   * The runtime information for the Storm application.
   */
  readonly runtime: StormRuntimeInfo;
  /**
   * The build information for the Storm application.
   */
  readonly build: StormBuildInfo;
  /**
   * The environment paths for storing things like data, config, logs, and cache in the current runtime environment.
   *
   * @remarks
   * On macOS, directories are generally created in \`~/Library/Application Support/<name>\`.
   * On Windows, directories are generally created in \`%AppData%/<name>\`.
   * On Linux, directories are generally created in \`~/.config/<name>\` - this is determined via the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/).
   *
   * If the \`STORM_DATA_DIR\`, \`STORM_CONFIG_DIR\`, \`STORM_CACHE_DIR\`, \`STORM_LOG_DIR\`, or \`STORM_TEMP_DIR\` environment variables are set, they will be used instead of the default paths.
   */
  readonly paths: StormEnvPaths;
  /**
   * The current payload object for the Storm application.
   */
  readonly payload: TPayload;
  /**
   * The current meta object.
   */
  readonly meta: Record<string, any>;
  /**
   * The root application logger for the Storm Stack application.
   */
  readonly log: IStormLog;
  /**
   * The root [unstorage](https://unstorage.unjs.io/) storage to use for Storm Stack application.
   */
  readonly storage: import("unstorage").Storage<
    import("unstorage").StorageValue
  >;
  /**
   * A function to emit an event to a processing queue.
   */
  emit: <TEvent extends IStormEvent<string, any>>(event: TEvent) => void;
  /**
   * A store that exists on the StormContext for internal use.
   *
   * @remarks
   * Please do not use this in application code as it is likely to change
   *
   * @internal
   */
  __internal: Internal_StormContextStore;
};

/**
 * The environment paths for storing things like data, config, logs, and cache in the current runtime environment.
 *
 * @remarks
 * On macOS, directories are generally created in \`~/Library/Application Support/<name>\`.
 * On Windows, directories are generally created in \`%AppData%/<name>\`.
 * On Linux, directories are generally created in \`~/.config/<name>\` - this is determined via the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/).
 *
 * If the \`STORM_DATA_DIR\`, \`STORM_CONFIG_DIR\`, \`STORM_CACHE_DIR\`, \`STORM_LOG_DIR\`, or \`STORM_TEMP_DIR\` environment variables are set, they will be used instead of the default paths.
 */
interface StormEnvPaths {
  data: string;
  config: string;
  cache: string;
  log: string;
  temp: string;
}

/**
 * Interface representing the Storm error options.
 */
interface StormErrorOptions {
  /**
   * The error name.
   */
  name?: string;
  /**
   * The error code
   */
  code: number;
  /**
   * The error message parameters.
   */
  params?: string[];
  /**
   * The error cause.
   */
  cause?: unknown;
  /**
   * The error stack.
   */
  stack?: string;
  /**
   * The type of error.
   *
   * @defaultValue "exception"
   */
  type?: ErrorType;
  /**
   * Additional data to be included with the error.
   */
  data?: any;
}

/**
 * Interface representing the dynamic runtime information for the Storm application.
 */
interface StormRuntimeInfo {
  /**
   * Indicates if the application is running in debug mode.
   */
  isDebug: boolean;
  /**
   * Indicates if the application is running in a test environment.
   */
  isTest: boolean;
  /**
   * Indicates if the application is running on Node.js.
   */
  isNode: boolean;
  /**
   * Indicates if the application is running on a Windows operating system.
   */
  isWindows: boolean;
  /**
   * Indicates if the application is running on a Linux operating system.
   */
  isLinux: boolean;
  /**
   * Indicates if the application is running on a macOS operating system.
   */
  isMacOS: boolean;
  /**
   * Indicates if the application is running in a Continuous Integration (CI) environment.
   */
  isCI: boolean;
  /**
   * Indicates if the current process is interactive
   *
   * @see https://github.com/sindresorhus/is-interactive/blob/dc8037ae1a61d828cfb42761c345404055b1e036/index.js
   *
   * @remarks
   * Checks `stdin` for our prompts - It checks that the stream is TTY, not a dumb terminal
   */
  isInteractive: boolean;
  /**
   * Indicates if the application has a TTY (teletypewriter) interface.
   */
  hasTTY: boolean;
  /**
   * Indicates if the application is running in a minimal environment.
   */
  isMinimal: boolean;
  /**
   * Indicates if Unicode characters are supported in the terminal.
   */
  isUnicodeSupported: boolean;
  /**
   * Indicates if color output is supported in the terminal.
   */
  isColorSupported: boolean;
  /**
   * Indicates if the application is running in a server environment.
   */
  isServer: boolean;
}

type SuccessMessageDetails = MessageDetails<"success">;

type TeardownFunction = () => MaybePromise<
  IStormError | void | null | undefined
>;

type ValidationDetail =
  | {
      code: string;
      message?: string;
      type: ValidationDetailType;
      params?: Record<string, any>;
    }
  | {
      code?: string;
      message: string;
      type: ValidationDetailType;
      params?: Record<string, any>;
    };

type ValidationDetailType = "help" | "error" | "warning" | "info" | "success";

type ValidatorFunction<
  TPayload extends IStormPayload,
  TContext extends StormContext<StormBaseVariables, any, TPayload>
> = (context: TContext) => MaybePromise<IStormError | void | null | undefined>;

type WarningMessageDetails = MessageDetails<"warning">;

type StormVariables = Omit<
  StormBaseVariables,
  | "STORM_STACK_LOCAL"
  | "APP_NAME"
  | "APP_VERSION"
  | "BUILD_ID"
  | "BUILD_TIMESTAMP"
  | "BUILD_CHECKSUM"
  | "RELEASE_ID"
  | "RELEASE_TAG"
  | "TERM"
  | "TERM_PROGRAM"
  | "TERM_PROGRAM_VERSION"
  | "TERMINAL_EMULATOR"
  | "WT_SESSION"
  | "TERMINUS_SUBLIME"
  | "ConEmuTask"
  | "CURSOR_TRACE_ID"
  | "VTE_VERSION"
  | "RUN_ID"
  | "AGOLA_GIT_REF"
  | "AC_APPCIRCLE"
  | "APPVEYOR"
  | "CODEBUILD"
  | "TF_BUILD"
  | "bamboo_planKey"
  | "BITBUCKET_COMMIT"
  | "BITRISE_IO"
  | "BUDDY_WORKSPACE_ID"
  | "BUILDKITE"
  | "CIRCLECI"
  | "CIRRUS_CI"
  | "CF_BUILD_ID"
  | "CM_BUILD_ID"
  | "CI_NAME"
  | "DRONE"
  | "DSARI"
  | "EARTHLY_CI"
  | "EAS_BUILD"
  | "GERRIT_PROJECT"
  | "GITEA_ACTIONS"
  | "GITHUB_ACTIONS"
  | "GITLAB_CI"
  | "GOCD"
  | "BUILDER_OUTPUT"
  | "HARNESS_BUILD_ID"
  | "JENKINS_URL"
  | "LAYERCI"
  | "MAGNUM"
  | "NETLIFY"
  | "NEVERCODE"
  | "PROW_JOB_ID"
  | "RELEASE_BUILD_ID"
  | "RENDER"
  | "SAILCI"
  | "HUDSON"
  | "SCREWDRIVER"
  | "SEMAPHORE"
  | "SOURCEHUT"
  | "STRIDER"
  | "TASK_ID"
  | "TEAMCITY_VERSION"
  | "TRAVIS"
  | "VELA"
  | "NOW_BUILDER"
  | "APPCENTER_BUILD_ID"
  | "CI_XCODE_PROJECT"
  | "XCS"
  | "LOCALAPPDATA"
  | "APPDATA"
  | "XDG_DATA_HOME"
  | "XDG_CONFIG_HOME"
  | "XDG_CACHE_HOME"
  | "XDG_STATE_HOME"
  | "XDG_RUNTIME_DIR"
> &
  Readonly<
    Pick<
      StormBaseVariables,
      | "APP_NAME"
      | "APP_VERSION"
      | "BUILD_ID"
      | "BUILD_TIMESTAMP"
      | "BUILD_CHECKSUM"
      | "RELEASE_ID"
      | "RELEASE_TAG"
      | "TERM"
      | "TERM_PROGRAM"
      | "TERM_PROGRAM_VERSION"
      | "TERMINAL_EMULATOR"
      | "WT_SESSION"
      | "TERMINUS_SUBLIME"
      | "ConEmuTask"
      | "CURSOR_TRACE_ID"
      | "VTE_VERSION"
      | "RUN_ID"
      | "AGOLA_GIT_REF"
      | "AC_APPCIRCLE"
      | "APPVEYOR"
      | "CODEBUILD"
      | "TF_BUILD"
      | "bamboo_planKey"
      | "BITBUCKET_COMMIT"
      | "BITRISE_IO"
      | "BUDDY_WORKSPACE_ID"
      | "BUILDKITE"
      | "CIRCLECI"
      | "CIRRUS_CI"
      | "CF_BUILD_ID"
      | "CM_BUILD_ID"
      | "CI_NAME"
      | "DRONE"
      | "DSARI"
      | "EARTHLY_CI"
      | "EAS_BUILD"
      | "GERRIT_PROJECT"
      | "GITEA_ACTIONS"
      | "GITHUB_ACTIONS"
      | "GITLAB_CI"
      | "GOCD"
      | "BUILDER_OUTPUT"
      | "HARNESS_BUILD_ID"
      | "JENKINS_URL"
      | "LAYERCI"
      | "MAGNUM"
      | "NETLIFY"
      | "NEVERCODE"
      | "PROW_JOB_ID"
      | "RELEASE_BUILD_ID"
      | "RENDER"
      | "SAILCI"
      | "HUDSON"
      | "SCREWDRIVER"
      | "SEMAPHORE"
      | "SOURCEHUT"
      | "STRIDER"
      | "TASK_ID"
      | "TEAMCITY_VERSION"
      | "TRAVIS"
      | "VELA"
      | "NOW_BUILDER"
      | "APPCENTER_BUILD_ID"
      | "CI_XCODE_PROJECT"
      | "XCS"
      | "LOCALAPPDATA"
      | "APPDATA"
      | "XDG_DATA_HOME"
      | "XDG_CONFIG_HOME"
      | "XDG_CACHE_HOME"
      | "XDG_STATE_HOME"
      | "XDG_RUNTIME_DIR"
    >
  >;
const $storm: StormContext<StormVariables>;

declare module "storm:storage/cloudflare-kv-storage" {
  declare const _default: import("unstorage").Driver<
    import("unstorage/drivers/cloudflare-kv-binding").KVOptions,
    KVNamespace<string>
  >;
  export default _default;
}

declare module "storm:storage" {
  /**
   * The storage module provides a unified storage interface for the Storm Stack runtime.
   *
   * @module storm:storage
   */
  export const storage: import("unstorage").Storage<
    import("unstorage").StorageValue
  >;
}

declare module "storm:error" {
  /**
   * The Storm Stack error module provides a custom error class and utility functions to support error handling
   *
   * @module storm:error
   */

  /**
   * Get the default error code for the given error type.
   *
   * @param _type - The error type.
   * @returns The default error code.
   */
  export function getDefaultCode(_type: ErrorType): number;
  /**
   * Get the default error name for the given error type.
   *
   * @param type - The error type.
   * @returns The default error name.
   */
  export function getDefaultErrorName(type: ErrorType): string;
  /**
   * Checks if `value` is an {@link Error}, `EvalError`, `RangeError`, `ReferenceError`,
   * `SyntaxError`, `TypeError`, or `URIError` object.
   *
   * @example
   * ```typescript
   * isError(new Error)
   * // => true
   *
   * isError(Error)
   * // => false
   * ```
   *
   * @param value - The value to check.
   * @returns Returns `true` if `value` is an error object, else `false`.
   */
  export function isError(value: unknown): value is Error;
  /**
   * Type-check to determine if `value` is a {@link StormError} object
   *
   * @param value - the object to check
   * @returns Returns `true` if `value` is a {@link StormError} object, else `false`.
   */
  export function isStormError(value: unknown): value is StormError;
  /**
   * Creates a new {@link StormError} instance from an unknown cause value
   *
   * @param cause - The cause of the error in an unknown type
   * @param type - The type of the error
   * @param data - Additional data to be passed with the error
   * @returns The cause of the error in a {@link StormError} object
   */
  export function createStormError(
    cause: unknown,
    type?: ErrorType,
    data?: any
  ): StormError;
  /**
   * A wrapper around the base JavaScript Error class to be used in Storm Stack applications
   */
  export class StormError extends Error implements IStormError {
    __proto__: ErrorConstructor;
    /**
     * The error code
     */
    code: number;
    /**
     * The error message parameters
     */
    params: string[];
    /**
     * The type of error event
     */
    type: ErrorType;
    /**
     * Additional data to be passed with the error
     */
    data?: any;
    /**
     * The StormError constructor
     *
     * @param options - The options for the error
     * @param type - The type of error
     */
    constructor(optionsOrMessage: StormErrorOptions | string, type?: ErrorType);
    /**
     * The cause of the error
     */
    get cause(): IStormError | undefined;
    /**
     * The cause of the error
     */
    set cause(cause: unknown);
    /**
     * The parsed stack traces from the raw stack string
     *
     * @returns The parsed stack traces
     */
    get stacktrace(): ParsedStacktrace[];
    /**
     * Prints a displayable/formatted stack trace
     *
     * @returns The stack trace string
     */
    get stack(): string;
    /**
     * Store the stack trace
     */
    set stack(stack: string);
    /**
     * The unformatted stack trace
     *
     * @returns The stack trace string
     */
    get originalStack(): string;
    /**
     * The unformatted stack trace
     *
     * @returns The stack trace string
     */
    set originalStack(stack: string);
    /**
     * A URL to a page that displays the error message details
     */
    get url(): string;
    /**
     * Prints the display error message string
     *
     * @param includeData - Whether to include the data in the error message
     * @returns The display error message string
     */
    toDisplay(includeData?: boolean): string;
    /**
     * Prints the error message and stack trace
     *
     * @param stacktrace - Whether to include the stack trace in the error message
     * @param includeData - Whether to include the data in the error message
     * @returns The error message and stack trace string
     */
    toString(stacktrace?: boolean, includeData?: boolean): string;
  }
}

declare module "storm:context" {
  /**
   * This module provides the Storm Stack context and a hook to access it in the application.
   *
   * @module storm:context
   */

  export const STORM_ASYNC_CONTEXT: import("unctx").UseContext<StormContext>;
  /**
   * Get the Storm context for the current application.
   *
   * @returns The Storm context for the current application.
   * @throws If the Storm context is not available.
   */
  export function useStorm(): StormContext;
}

declare module "storm:result" {
  /**
   * The result module provides the {@link StormResult} class, which is used to represent the result of a payload execution.
   *
   * @module storm:result
   */

  /**
   * A base result class used by the Storm Stack runtime.
   */
  export class StormResult<TData extends any | StormError = any | StormError>
    implements IStormResult<TData>
  {
    /**
     * Create a new result.
     *
     * @remarks
     * **IMPORTANT:** This function uses the storm context object - never use this function outside of the context wrapper/tree since the context will not be available.
     *
     * @param data - The result data
     */
    static create<TData>(data: TData): StormResult<TData>;
    /**
     * The result meta.
     */
    readonly meta: Record<string, any>;
    /**
     * The result data.
     */
    data: TData;
    /**
     * The payload identifier.
     */
    readonly payloadId: string;
    /**
     * The response created timestamp.
     */
    readonly timestamp: number;
    /**
     * An indicator of whether the response was successful.
     */
    get success(): boolean;
    /**
     * Create a new result.
     *
     * @param payloadId - The payload identifier.
     * @param meta - The current context's metadata.
     * @param data - The result data
     */
    constructor(payloadId: string, meta: Record<string, any>, data: TData);
  }
}

declare module "storm:id" {
  /**
   * The ID module provides a set of utilities for generating unique identifiers.
   *
   * @module storm:id
   */
  /**
   * Generate a random string
   *
   * @param array - The array to fill with random values
   * @returns The array filled with random values
   */
  export function getRandom(array: Uint8Array): Uint8Array<ArrayBufferLike>;
  /**
   * A platform agnostic version of the [nanoid](https://github.com/ai/nanoid) package with some modifications.
   *
   * @param size - The size of the string to generate
   * @returns A unique identifier following the nanoid format
   */
  export function uniqueId(size?: number): string;
}

declare module "storm:payload" {
  /**
   * The payload module provides a base payload class used by the Storm Stack runtime.
   *
   * @module storm:payload
   */

  /**
   * A base payload class used by the Storm Stack runtime.
   */
  export class StormPayload<TData = any> implements IStormPayload<TData> {
    /**
     * The data associated with the payload.
     */
    readonly data: TData;
    /**
     * The payload identifier.
     */
    readonly id: string;
    /**
     * The payload created timestamp.
     */
    readonly timestamp: number;
    /**
     * Create a new payload object.
     *
     * @param data - The payload data.
     */
    constructor(data: TData);
  }
}

declare module "storm:logs/console-info" {
  export const DATE_TIME_FORMAT: Intl.DateTimeFormat;
  declare const sink: (record: LogRecord) => void;
  export default sink;
}

declare module "storm:log" {
  /**
   * The log module provides a unified logging interface for Storm Stack applications.
   *
   * @module storm:log
   */

  /**
   * Returns a filter that accepts log records with the specified level.
   *
   * @param level - The level to filter by. If `null`, the filter will reject all records.
   * @returns The filter.
   */
  export function getLevelFilter(level: LogLevel | null): LogFilter;
  /**
   * Parses a {@link LogLevel | log level} from a string.
   *
   * @param level - The {@link LogLevel | log level} as a string. This is case-insensitive.
   * @returns The {@link LogLevel | log level}.
   */
  export function parseLogLevel(level: string): LogLevel;
  /**
   * Checks if a string is a valid {@link LogLevel | log level}. This function can be used as a type guard to narrow the type of a string to a {@link LogLevel}.
   *
   * @param level - The {@link LogLevel | log level} as a string. This is case-sensitive.
   * @returns `true` if the string is a valid {@link LogLevel | log level}.
   */
  export function isLogLevel(level: string): level is LogLevel;
  /**
   * The StormLog class that's used for writing logs during Storm Stack applications.
   */
  export class StormLog implements IStormLog {
    readonly filters: LogFilter[];
    lowestLogLevel: LogLevel | null;
    constructor();
    with(properties: Record<string, unknown>): IStormLog;
    filter(record: LogRecord): boolean;
    sinks(level?: LogLevel): Iterable<LogSink>;
    emit(record: LogRecord, bypassSinks?: Set<LogSink>): void;
    log(
      level: LogLevel,
      rawMessage: string,
      properties: Record<string, unknown> | (() => Record<string, unknown>),
      bypassSinks?: Set<LogSink>
    ): void;
    logLazily(
      level: LogLevel,
      callback: LogCallback,
      properties?: Record<string, unknown>
    ): void;
    logTemplate(
      level: LogLevel,
      messageTemplate: TemplateStringsArray,
      values: unknown[],
      properties?: Record<string, unknown>
    ): void;
    debug(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    info(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    warn(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    error(
      message: TemplateStringsArray | string | LogCallback | Error,
      ...values: unknown[]
    ): void;
    fatal(
      message: TemplateStringsArray | string | LogCallback | Error,
      ...values: unknown[]
    ): void;
    protected getStore(): Record<string, unknown>;
  }
}

declare module "storm:init" {
  export default function init(): void;
}

declare module "storm:event" {
  /**
   * The Storm Stack event module.
   *
   * @module storm:event
   */

  /**
   * A base event class used by the Storm Stack runtime.
   */
  export class StormEvent<TEventType extends string = string, TEventData = any>
    extends StormPayload<TEventData>
    implements IStormEvent<TEventType, TEventData>
  {
    /**
     * The payload identifier.
     */
    readonly payloadId: string;
    /**
     * The event type.
     */
    readonly type: TEventType;
    /**
     * The event version.
     */
    readonly version: string;
    /**
     * The event label.
     *
     * @remarks
     * The label format is "{type}-v{version}"
     */
    get label(): string;
    /**
     * Creates a new event.
     *
     * @param type - The event type.
     * @param data - The event data.
     */
    constructor(type: TEventType, data: TEventData);
  }
}

declare module "storm:env" {
  /**
   * This module provides the runtime environment information for the Storm Stack application.
   *
   * @module storm:env
   */

  /** Detect if stdout.TTY is available */
  export const hasTTY: boolean;
  /** Detect if the application is running in a CI environment */
  export const isCI: boolean;
  /** Detect the `NODE_ENV` environment variable */
  export const mode: string;
  /** Detect if the application is running in production mode */
  export const isProduction: boolean;
  /** Detect if the application is running in staging mode */
  export const isStaging: boolean;
  /** Detect if the application is running in development mode */
  export const isDevelopment: boolean;
  /** Detect if the application is running in debug mode */
  export const isDebug: boolean;
  /** Detect if the application is running in test mode */
  export const isTest: boolean;
  /** Detect if MINIMAL environment variable is set, running in CI or test or TTY is unavailable */
  export const isMinimal: boolean;
  /** Detect if the runtime platform is Windows */
  export const isWindows: boolean;
  /** Detect if the runtime platform is Linux */
  export const isLinux: boolean;
  /** Detect if the runtime platform is macOS (darwin kernel) */
  export const isMacOS: boolean;
  /** Detect if the runtime platform is interactive */
  export const isInteractive: boolean;
  /** Detect if Unicode characters are supported */
  export const isUnicodeSupported: boolean;
  /** Detect if color is supported */
  export const isColorSupported: boolean;
  /**
   * Indicates if running in Node.js or a Node.js compatible runtime.
   *
   * @remarks
   * When running code in Bun and Deno with Node.js compatibility mode, `isNode` flag will be also `true`, indicating running in a Node.js compatible runtime.
   */
  export const isNode: boolean;
  /** The organization that maintains the application */
  export const organization = "storm-software";
  /** The current application */
  export const name = "examples-cloudflare-worker";
  /** The current application */
  export const version = "0.0.1";
  /**
   * The environment paths for storing things like data, config, logs, and cache in the current runtime environment.
   *
   * @remarks
   * On macOS, directories are generally created in `~/Library/Application Support/<name>`.
   * On Windows, directories are generally created in `%AppData%/<name>`.
   * On Linux, directories are generally created in `~/.config/<name>` - this is determined via the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/).
   *
   * If the `STORM_DATA_DIR`, `STORM_CONFIG_DIR`, `STORM_CACHE_DIR`, `STORM_LOG_DIR`, or `STORM_TEMP_DIR` environment variables are set, they will be used instead of the default paths.
   */
  export const paths: StormEnvPaths;
  /** The static build information collection */
  export const build: StormBuildInfo;
  /** The dynamic runtime information collection */
  export const runtime: StormRuntimeInfo;
}

declare module "storm:app" {
  /**
   * A module containing a wrapper for the application entry point.
   *
   * @remarks
   * This module provides a function to wrap an application entry point with the necessary context and error handling.
   *
   * @module storm:app
   */

  /**
   * Wrap an application entry point with the necessary context and error handling.
   *
   * @param handler - The handler function for the application.
   * @returns A function that takes an payload and returns a result or a promise of a result.
   */
  export function withContext<TInput = any, TOutput = any>(
    handler: HandlerFunction<TInput, TOutput>
  ): (input: TInput) => Promise<StormResult<TOutput | StormError>>;
}
