/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import { colors } from "../../../runtime/cli";
import { StormPayload } from "../../../runtime/payload";
import { StormVariables } from "../../../runtime/vars";

export interface VarsGetPayload {
  /**
   * The name of the variable to retrieve from the variables store.
   */
  name: string;
}

/**
 * Retrieves a configuration parameter from the variables store.
 *
 * @param payload - The payload object containing the variable name to retrieve.
 */
async function handler(payload: StormPayload<VarsGetPayload>) {
  const varsFile = await $storm.storage.getItem(`vars:vars.json`);
  if (varsFile === undefined) {
    console.error(
      ` ${colors.red("✘")} ${colors.white(`Variables file was not found`)}`
    );
    return;
  }

  const vars = deserialize<StormVariables>(varsFile);
  if (vars?.[payload.data.name] === undefined) {
    console.error(
      ` ${colors.red("✘")} ${colors.white(`Variable Name \`${payload.data.name}\` not found`)}`
    );
    return;
  }

  console.log(
    `${colors.bold(`${payload.data.name}:`)} ${vars[payload.data.name]}`
  );
}

export default handler;
