/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import { colors } from "../../../runtime/cli";

export interface VarsGetPayload {
  /**
   * The key to retrieve from the variables.
   */
  key: string;
}

/**
 * Retrieves a configuration parameter from the variables store.
 *
 * @param payload - The payload object containing the variable key to retrieve.
 */
async function handler(payload: StormPayload<VarsGetPayload>) {
  const varsFile = await $storm.storage.getItem(`vars:vars.json`);
  if (varsFile === undefined) {
    console.error(
      ` ${colors.red("✖")} ${colors.redBright(`Variables file was not found`)}`
    );
    return;
  }

  const vars = deserialize<StormVariables>(varsFile);
  if (vars?.[payload.data.key] === undefined) {
    console.error(
      ` ${colors.red("✖")} ${colors.redBright(`Variable Key \`${payload.data.key}\` not found`)}`
    );
    return;
  }

  console.log(
    `${colors.bold(`${payload.data.key}:`)} ${vars[payload.data.key]}`
  );
}

export default handler;
