/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import handle from "handle";
import { withContext } from "../../../runtime/app";
import {
  colors,
  prompt,
  renderBanner,
  renderFooter
} from "../../../runtime/cli";
import { getRuntimeInfo } from "../../../runtime/env";

export interface VarsGetPayload {
  help: boolean;
  version: boolean;
  interactive: boolean;
  noInteractive: boolean;
  noBanner: boolean;
  verbose: boolean;
  key: string;
}

/**
 * Renders the Variables - Get command usage information.
 *
 * @param includeCommands - Whether to include rendering sub-commands.
 * @returns The rendered string displaying usage information.
 */
export function renderUsage(includeCommands = true) {
  return `${colors.bold("Variables - Get")}

${colors.dim("Retrieves a configuration parameter from the variables store.")}

  ${colors.bold("Usage:")}
    examples-cli vars get <key> [options] 

  ${colors.bold("Options:")}
    --help, -h, -?                   ${colors.dim("Show help information. [default: false]")} 
    --version, -v                    ${colors.dim("Show the version of the application. [default: false]")} 
    --interactive, -i, --interact    ${colors.dim("Enable interactive mode (will be set to false if running in a CI pipeline). [default: true]")} 
    --no-interactive, --no-interact  ${colors.dim("Disable interactive mode (will be set to true if running in a CI pipeline). [default: false]")} 
    --no-banner                      ${colors.dim("Hide the banner displayed while running the CLI application (will be set to true if running in a CI pipeline). [default: false]")} 
    --verbose, -v                    ${colors.dim("Enable verbose output. [default: false]")} 
    --key <key>, -k <key>            ${colors.dim("The key to retrieve from the variables.")}
`;
}

const handleCommand = withContext<VarsGetPayload>(handle);

/**
 * The entry point for the Variables - Get command.
 */
async function handler() {
  try {
    const args = parseArgs(process.argv.slice(4), {
      boolean: [
        "help",
        "h",
        "?",
        "version",
        "v",
        "interactive",
        "i",
        "interact",
        "no-interactive",
        "no-interact",
        "no-banner",
        "",
        "verbose",
        "v"
      ],
      alias: {
        help: ["help", "HELP", "h", "H", "?", "?"],
        version: ["version", "VERSION", "v", "V"],
        interactive: [
          "interactive",
          "INTERACTIVE",
          "i",
          "I",
          "interact",
          "INTERACT"
        ],
        noInteractive: [
          "no-interactive",
          "NO-INTERACTIVE",
          "no-interact",
          "NO-INTERACT"
        ],
        noBanner: ["no-banner", "NO-BANNER"],
        verbose: ["verbose", "VERBOSE", "v", "V"],
        key: ["key", "KEY", "k", "K"]
      }
    });

    if (args["version"] || args["v"]) {
      console.log($storm.vars.APP_VERSION);
    } else {
      const runtimeInfo = getRuntimeInfo();
      const isVerbose =
        args["verbose"] ?? Boolean(process.env.EXAMPLES_CLI_VERBOSE);
      const isInteractive =
        args["interactive"] !== false &&
        args["no-interactive"] !== true &&
        Boolean(process.env.EXAMPLES_CLI_INTERACTIVE) &&
        runtimeInfo.isInteractive &&
        !runtimeInfo.isCI;

      if (args["no-banner"] !== true && !runtimeInfo.isCI) {
        console.log(
          renderBanner(
            "Variables - Get",
            "Retrieves a configuration parameter from the variables store."
          )
        );
        console.log("");
      }

      if (args["help"] || args["h"] || args["?"]) {
        console.log(renderUsage(true));
        console.log("");
        console.log(renderFooter());
        console.log("");
      } else {
        if (isVerbose) {
          console.log(
            colors.dim(
              ` > Writing verbose output to console - as a result of the ${args["verbose"] ? 'user provided "verbose" option' : "EXAMPLES_CLI_VERBOSE environment variable"} `
            )
          );
          console.log("");

          if (isInteractive) {
            console.log(colors.dim(" > Running in interactive mode..."));
          } else {
            console.log(colors.dim(" > Running in non-interactive mode..."));
          }
          console.log("");
        }

        if (args["key"] === undefined && process.env.EXAMPLES_CLI_KEY) {
          args["key"] = process.env.EXAMPLES_CLI_KEY;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the key option to ${process.env.EXAMPLES_CLI_KEY} (via the EXAMPLES_CLI_KEY environment variable) `
              )
            );
          }
        }

        if (args["key"] === undefined) {
          if (isInteractive) {
            args["key"] = await prompt<string>(
              "The key to retrieve from the variables",
              {
                type: "text"
              }
            );
          } else {
            args["key"] = undefined;
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the key option to undefined (via it's default value) `
                )
              );
            }
          }
        }

        await handleCommand(deserialize<VarsGetPayload>(args));
      }
    }
  } catch (err) {
    console.error(
      ` ${colors.red("✖")} ${colors.redBright(`Error occurred while processing Variables - Get command.`)}`
    );
  }
}

export default handler;
