/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

/// <reference types="@storm-stack/types" />
/// <reference types="@storm-stack/types/node" />

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

declare global {
  const parseArgs: (typeof import("../runtime/cli"))["parseArgs"];

  const colors: (typeof import("../runtime/cli"))["colors"];
  const getColor: (typeof import("../runtime/cli"))["getColor"];
  type ColorName = import("../runtime/cli").ColorName;

  const link: (typeof import("../runtime/cli"))["link"];
  type LinkOptions = import("../runtime/cli").LinkOptions;  

  const prompt: (typeof import("../runtime/cli"))["prompt"];
  type TextPromptOptions = import("../runtime/cli").TextPromptOptions;
  type ConfirmPromptOptions = import("../runtime/cli").ConfirmPromptOptions;
  type SelectPromptOptions = import("../runtime/cli").SelectPromptOptions;
  type MultiSelectPromptOptions = import("../runtime/cli").MultiSelectPromptOptions;
}

export {};
