/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

/// <reference types="../../../../dist/packages/types" />
/// <reference types="../../../../dist/packages/types/node" />

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

declare module "storm:cli" {
  const parseArgs: (typeof import("../runtime/cli"))["parseArgs"];
  const colors: (typeof import("../runtime/cli"))["colors"];
  const getColor: (typeof import("../runtime/cli"))["getColor"];
  const link: (typeof import("../runtime/cli"))["link"];
  const renderBanner: (typeof import("../runtime/cli"))["renderBanner"];
  const prompt: (typeof import("../runtime/cli"))["prompt"];

  export { colors,getColor,link,parseArgs,prompt,renderBanner };
}
