
// Generated by @storm-software/untyped
// Do not edit this file directly

export interface StormStackBaseExecutorSchema {
 /**
  * Output Path
  * 
  * The output path for the build
  * 
  * @default "dist/{projectRoot}"
  * 
  * @format path
 */
 outputPath?: string,

 /**
  * TypeScript Configuration File
  * 
  * The path to the tsconfig file
  * 
  * @default "{projectRoot}/tsconfig.json"
  * 
  * @format path
 */
 tsconfig?: string,

 /**
  * Mode
  * 
  * The build mode
  * 
  * 
  * @enum development,staging,production
 */
 mode?: string,

 /**
  * Skip Installs
  * 
  * Skip installing dependencies during prepare stage
  * 
 */
 skipInstalls?: boolean,

 /**
  * Log Level
  * 
  * The log level to use for the build process
  * 
  * 
  * @enum error,success,silent,fatal,warn,info,debug,trace,all
 */
 logLevel?: string,
}

