/// <reference types="@storm-stack/core/shared" />
/// <reference types="@storm-stack/core/node" />

/* eslint-disable */
// biome-ignore lint: disable

// Generated with Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

declare module "storm:env" {
  /**
   * The Storm Stack environment configuration module provides an interface to define environment configuration parameters.
   *
   * @module storm:env
   */

  /**
   *
   *
   * @title Object
   *
   *
   */
  export interface StormEnvBase extends StormEnvInterface {
    /**
     *
     *
     * @domain cli
     *
     *
     */
    ARGV?: Array<string>;
    /**
     * The inverse of the no-banner option.
     *
     * @domain cli
     *
     *
     */
    BANNER?: boolean;
    /**
     * The Storm Stack application's cached data directory.
     *
     * @title Cache Directory
     *
     *
     */
    CACHE_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a continuous integration environment.
     *
     * @title Continuous Integration
     * @alias CONTINUOUS_INTEGRATION
     *
     *
     */
    CI: boolean;
    /**
     * The configuration file to append the completion script to.
     *
     * @domain cli
     *
     *
     */
    CONFIG?: string | true;
    /**
     * The Storm Stack application's configuration data directory.
     *
     * @title Configuration Directory
     *
     *
     */
    CONFIG_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a continuous integration environment.
     *
     * @title Continuous Integration
     * @alias CI
     *
     *
     */
    CONTINUOUS_INTEGRATION: boolean;
    /**
     * The Storm Stack application's runtime data directory.
     *
     * @title Data Directory
     *
     *
     */
    DATA_DIR?: string;
    /**
     * Indicates if the application is running in debug mode.
     *
     *
     *
     */
    DEBUG: boolean;
    /**
     * The default locale to be used in the application.
     *
     *
     *
     */
    DEFAULT_LOCALE: string;
    /**
     * The default timezone for the application.
     *
     *
     *
     */
    DEFAULT_TIMEZONE: string;
    /**
     * A variable that specifies the [Devenv](https://devenv.sh/) runtime directory.
     *
     *
     *
     */
    DEVENV_RUNTIME?: string;
    /**
     * The environment the application is running in. This value will be populated with the value of `MODE` if not provided.
     *
     * @title ENVIRONMENT
     * @alias ENVIRONMENT
     *
     *
     */
    ENV: string;
    /**
     * The environment the application is running in. This value will be populated with the value of `MODE` if not provided.
     *
     * @alias ENV
     *
     *
     */
    ENVIRONMENT: string;
    /**
     * A web page to lookup error messages and display additional information given an error code.
     *
     * @title Error Details URL
     *
     *
     */
    ERROR_URL: string;
    /**
     * An indicator that specifies the current runtime is a force color environment.
     *
     *
     *
     */
    FORCE_COLOR: boolean | number;
    /**
     * An indicator that specifies the current runtime should force hyperlinks in terminal output.
     *
     *
     *
     */
    FORCE_HYPERLINK: boolean | number;
    /**
     * Show help information.
     *
     * @domain cli
     *
     *
     */
    HELP?: boolean;
    /**
     * Indicates if error data should be included.
     *
     *
     *
     */
    INCLUDE_ERROR_DATA: boolean;
    /**
     * The inverse of the no-interactive option.
     *
     * @domain cli
     *
     *
     */
    INTERACTIVE?: boolean;
    /**
     * The Storm Stack application's logging directory.
     *
     * @title Log Directory
     *
     *
     */
    LOG_DIR?: string;
    /**
     * The default lowest log level to accept. If `null`, the logger will reject all records. This value only applies if `lowestLogLevel` is not provided to the `logs` configuration.
     *
     *
     *
     */
    LOG_LEVEL?: "debug" | "info" | "warning" | "error" | "fatal" | null;
    /**
     * An indicator that specifies the current runtime is a minimal environment.
     *
     *
     *
     */
    MINIMAL: boolean;
    /**
     * The mode in which the application is running.
     *
     * @alias NODE_ENV
     *
     *
     */
    MODE: "development" | "test" | "production";
    /**
     * The name of the library.
     *
     * @domain cli
     *
     *
     */
    NAME?: string;
    /**
     * Hide the banner displayed while running the CLI application (will be set to true if running in a CI pipeline).
     *
     * @domain cli
     *
     *
     */
    NO_BANNER?: boolean;
    /**
     * An indicator that specifies the current runtime is a no color environment.
     *
     *
     *
     */
    NO_COLOR: boolean;
    /**
     * Disable interactive mode (will be set to true if running in a CI pipeline).
     *
     * @title NO INTERACTIVE
     * @alias NO_INTERACTIVE
     * @domain cli
     *
     *
     */
    NO_INTERACT?: boolean;
    /**
     * Disable interactive mode (will be set to true if running in a CI pipeline).
     *
     * @alias NO_INTERACT
     * @domain cli
     *
     *
     */
    NO_INTERACTIVE?: boolean;
    /**
     * The mode in which the application is running.
     *
     * @title MODE
     * @alias MODE
     *
     *
     */
    NODE_ENV: "development" | "test" | "production";
    /**
     * The name of the organization that maintains the application.
     *
     * @title ORGANIZATION
     * @alias ORGANIZATION
     *
     *
     */
    ORG: string;
    /**
     * The name of the organization that maintains the application.
     *
     * @alias ORG
     *
     *
     */
    ORGANIZATION: string;
    /**
     * The mode used for outputting results.- `memory`: Generated source code is stored in a virtual file system to reduce boilerplate.- `fs`: Outputs generated results to the local file system.
     *
     *
     *
     */
    OUTPUT_MODE?: "virtual" | "fs";
    /**
     * The name of the library.
     *
     * @domain cli
     *
     *
     */
    PACKAGE_NAME?: string;
    /**
     * The platform for which the application was built.
     *
     *
     *
     */
    PLATFORM: "node" | "neutral" | "browser";
    /**
     * The root directory of the Storm Stack project.
     *
     * @title ROOT
     * @alias ROOT
     * @domain cli
     *
     *
     */
    PROJECT?: string;
    /**
     * The root directory of the Storm Stack project.
     *
     * @alias PROJECT
     * @domain cli
     *
     *
     */
    ROOT?: string;
    /**
     * The path to write the completion script to.
     *
     * @domain cli
     *
     *
     */
    SCRIPT?: string | true;
    /**
     * The DSN for Sentry
     *
     *
     *
     */
    SENTRY_DSN: string;
    /**
     * Indicates if error stack traces should be captured.
     *
     *
     *
     */
    STACKTRACE: boolean;
    /**
     * The Storm Stack application's temporary data directory.
     *
     * @title Temporary Directory
     *
     *
     */
    TEMP_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a test environment.
     *
     *
     *
     */
    TEST: boolean;
    /**
     * Enable verbose output.
     *
     * @domain cli
     *
     *
     */
    VERBOSE?: boolean;
    /**
     * Show the version of the application.
     *
     * @domain cli
     *
     *
     */
    VERSION?: boolean;
    /**
     * The appcircle build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly AC_APPCIRCLE?: string;
    /**
     * The name of the agent running the application. This variable is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly AGENT_NAME?: string;
    /**
     * The agola git reference. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly AGOLA_GIT_REF?: string;
    /**
     * The name of the application.
     *
     * @readonly
     *
     *
     */
    readonly APP_NAME: string;
    /**
     * The version of the application.
     *
     * @readonly
     *
     *
     */
    readonly APP_VERSION: string;
    /**
     * The appcenter build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly APPCENTER_BUILD_ID?: string;
    /**
     * A variable that specifies the application data directory on Windows.
     *
     * @readonly
     *
     *
     */
    readonly APPDATA?: string;
    /**
     * The appveyor build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly APPVEYOR?: string;
    /**
     * The bamboo plan key. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly bamboo_planKey?: string;
    /**
     * The bitbucket commit. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly BITBUCKET_COMMIT?: string;
    /**
     * The bitrise build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly BITRISE_IO?: string;
    /**
     * The buddy workspace ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly BUDDY_WORKSPACE_ID?: string;
    /**
     * A checksum hash created during the build.
     *
     * @readonly
     *
     *
     */
    readonly BUILD_CHECKSUM: string;
    /**
     * The unique identifier for the build.
     *
     * @readonly
     *
     *
     */
    readonly BUILD_ID: string;
    /**
     * The timestamp the build was ran at.
     *
     * @readonly
     *
     *
     */
    readonly BUILD_TIMESTAMP: string;
    /**
     * The builder output build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly BUILDER_OUTPUT?: string;
    /**
     * The buildkite build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly BUILDKITE?: string;
    /**
     * The cf build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CF_BUILD_ID?: string;
    /**
     * The ci name. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CI_NAME?: string;
    /**
     * The xcode project build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CI_XCODE_PROJECT?: string;
    /**
     * The circleci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CIRCLECI?: string;
    /**
     * The cirrus-ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CIRRUS_CI?: string;
    /**
     * The cm build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CM_BUILD_ID?: string;
    /**
     * The codebuild build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly CODEBUILD?: string;
    /**
     * The color terminal type. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly COLORTERM?: string;
    /**
     * The ConEmu task name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly ConEmuTask?: string;
    /**
     * The cursor trace ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly CURSOR_TRACE_ID?: string;
    /**
     * The drone build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly DRONE?: string;
    /**
     * The dsari build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly DSARI?: string;
    /**
     * The earthly build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly EARTHLY_CI?: string;
    /**
     * The eas build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly EAS_BUILD?: string;
    /**
     * The gerrit project. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly GERRIT_PROJECT?: string;
    /**
     * The gitea actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly GITEA_ACTIONS?: string;
    /**
     * The github actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly GITHUB_ACTIONS?: string;
    /**
     * The gitlab ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly GITLAB_CI?: string;
    /**
     * The go cd build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly GOCD?: string;
    /**
     * The harness build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly HARNESS_BUILD_ID?: string;
    /**
     * The hudson build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly HUDSON?: string;
    /**
     * The jenkins url. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly JENKINS_URL?: string;
    /**
     * The layerci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly LAYERCI?: string;
    /**
     * A variable that specifies the current user's local application data directory on Windows.
     *
     * @readonly
     *
     *
     */
    readonly LOCALAPPDATA?: string;
    /**
     * The magnum build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly MAGNUM?: string;
    /**
     * The netlify build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly NETLIFY?: string;
    /**
     * The nevercode build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly NEVERCODE?: string;
    /**
     * The now builder build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly NOW_BUILDER?: string;
    /**
     * The prow job ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly PROW_JOB_ID?: string;
    /**
     * The release build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly RELEASE_BUILD_ID?: string;
    /**
     * The unique identifier for the release.
     *
     * @readonly
     *
     *
     */
    readonly RELEASE_ID: string;
    /**
     * The tag for the release. This is generally in the format of "\<APP_NAME\>\@\<APP_VERSION\>".
     *
     * @readonly
     *
     *
     */
    readonly RELEASE_TAG: string;
    /**
     * The render build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly RENDER?: string;
    /**
     * The unique identifier for the current run. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly RUN_ID?: string;
    /**
     * The sailci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly SAILCI?: string;
    /**
     * The screwdriver build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly SCREWDRIVER?: string;
    /**
     * The semaphore build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly SEMAPHORE?: string;
    /**
     * The sourcehut build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly SOURCEHUT?: string;
    /**
     * The spaceship build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly SPACESHIP_CI?: string;
    /**
     * An indicator that specifies the application is running in the local Storm Stack development environment.
     *
     * @readonly
     *
     *
     */
    readonly STORM_STACK_LOCAL: boolean;
    /**
     * An indicator used to skip version checks for installed packages.
     *
     * @readonly
     *
     *
     */
    readonly STORM_STACK_SKIP_VERSION_CHECK?: boolean;
    /**
     * The strider build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly STRIDER?: string;
    /**
     * The task ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly TASK_ID?: string;
    /**
     * The teamcity version. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly TEAMCITY_VERSION?: string;
    /**
     * The terminal type. This variable is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly TERM?: string;
    /**
     * The terminal program name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly TERM_PROGRAM?: string;
    /**
     * The terminal program version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly TERM_PROGRAM_VERSION?: string;
    /**
     * The terminal emulator name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly TERMINAL_EMULATOR?: string;
    /**
     * An indicator that specifies the current terminal is running Terminus Sublime. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly TERMINUS_SUBLIME?: boolean;
    /**
     * The task force build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly TF_BUILD?: string;
    /**
     * The travis build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly TRAVIS?: string;
    /**
     * The vela build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly VELA?: string;
    /**
     * The VTE version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly VTE_VERSION?: string;
    /**
     * The terminal emulator session ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     *
     */
    readonly WT_SESSION?: string;
    /**
     * The xcode server build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     *
     */
    readonly XCS?: string;
    /**
     * A variable that specifies the cache path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     *
     */
    readonly XDG_CACHE_HOME?: string;
    /**
     * A variable that specifies the configuration path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     *
     */
    readonly XDG_CONFIG_HOME?: string;
    /**
     * A variable that specifies the data path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     *
     */
    readonly XDG_DATA_HOME?: string;
    /**
     * A variable that specifies the runtime directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     *
     */
    readonly XDG_RUNTIME_DIR?: string;
    /**
     * A variable that specifies the state directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     *
     */
    readonly XDG_STATE_HOME?: string;
  }
  export type StormEnv = {
    [Key in keyof StormEnvBase as
      | Key
      | `NEXT_${Key}`
      | `ONE_${Key}`
      | `STORM_STACK_${Key}`
      | `STORM_${Key}`
      | `VERCEL_${Key}`
      | `VITE_${Key}`]: StormEnvBase[Key];
  };
  /**
   * The initial environment configuration state for the Storm Stack project.
   *
   * @title Object
   *
   *
   */
  export const initialEnv: Partial<StormEnvBase>;
  /**
   * The environment configuration serializer for the Storm Stack application.
   *
   * @see https://deepkit.io/docs/serialization/serializers
   *
   * @see https://github.com/marcj/untitled-code/blob/master/packages/type/src/serializer.ts#L1918
   *
   * @remarks
   * This serializer is used to serialize and deserialize the Storm Stack environment configuration.
   */
  export class EnvSerializer extends Serializer {
    constructor();
  }
  /**
   * Serialize a environment configuration object to JSON data objects (not a JSON string).
   *
   * @remarks
   * The resulting JSON object can be stringified using JSON.stringify().
   * @example
   * ```ts
   * const json = serializeEnv(env);
   * ```
   * @throws ValidationError when serialization or validation fails.
   *
   */
  export const serializeEnv: import("@deepkit/type").SerializeFunction<StormEnvBase>;
  /**
   * Deserialize a environment configuration object from JSON data objects to JavaScript objects, without running any validators.
   *
   * @remarks
   * Types that are already correct will be used as-is.
   * @example
   * ```ts
   * const env = deserializeEnv(json);
   * ```
   * @throws ValidationError when deserialization fails.
   *
   */
  export const deserializeEnv: import("@deepkit/type").SerializeFunction<
    any,
    StormEnvBase
  >;
  /**
   * Initializes the Storm Stack environment configuration module.
   *
   * @remarks
   * This function initializes the Storm Stack environment configuration object.
   * @param environmentConfig - The dynamic/runtime configuration - this could include the current environment variables or any other environment-specific
   *   settings provided by the runtime.
   * @returns The initialized Storm Stack configuration object.
   *
   */
  export function createEnv(environmentConfig?: Partial<StormEnv>): StormEnv;
  export const env: StormEnv;
  export type StormEnvBase = any[];
  export type StormEnv = any[];
}

declare module "storm:error" {
  /**
   * The Storm Stack error module provides a custom error class and utility functions to support error handling
   *
   * @module storm:error
   */

  /**
   * Get the default error code for the given error type.
   *
   * @param _ - The error type.
   * @returns The default error code.
   */
  export function getDefaultCode(_: ErrorType): number;
  /**
   * Get the default error name for the given error type.
   *
   * @param type - The error type.
   * @returns The default error name.
   */
  export function getDefaultErrorName(type: ErrorType): string;
  /**
   * Checks if `value` is an {@link Error}, `EvalError`, `RangeError`, `ReferenceError`,
   * `SyntaxError`, `TypeError`, or `URIError` object.
   *
   * @example
   * ```typescript
   * isError(new Error)
   * // => true
   *
   * isError(Error)
   * // => false
   * ```
   *
   * @param value - The value to check.
   * @returns Returns `true` if `value` is an error object, else `false`.
   */
  export function isError(value: unknown): value is Error;
  /**
   * Type-check to determine if `value` is a {@link StormError} object
   *
   * @param value - the object to check
   * @returns Returns `true` if `value` is a {@link StormError} object, else `false`.
   */
  export function isStormError(value: unknown): value is StormError;
  /**
   * Creates a new {@link StormError} instance from an unknown cause value
   *
   * @param cause - The cause of the error in an unknown type
   * @param type - The type of the error
   * @param data - Additional data to be passed with the error
   * @returns The cause of the error in a {@link StormError} object
   */
  export function createStormError(
    cause: unknown,
    type?: ErrorType,
    data?: any
  ): StormError;
  /**
   * A wrapper around the base JavaScript Error class to be used in Storm Stack applications
   */
  export class StormError extends Error implements StormErrorInterface {
    readonly [Symbol.name]: string;
    /**
     * Internal function to inherit the {@link Error} prototype.
     *
     * @internal
     */
    __proto__: Error;
    /**
     * The error code
     */
    code: number;
    /**
     * The error message parameters
     */
    params: string[];
    /**
     * The type of error event
     */
    type: ErrorType;
    /**
     * Additional data to be passed with the error
     */
    data?: any;
    /**
     * The string tag for the error
     */
    readonly [Symbol.toStringTag]: string;
    /**
     * The StormError constructor
     *
     * @param options - The options for the error
     * @param type - The type of error
     */
    constructor(optionsOrMessage: StormErrorOptions | string, type?: ErrorType);
    /**
     * A string that uniquely identifies the error
     *
     * @remarks
     * The `id` property is a string that uniquely identifies the error. This string is generated based off the error type and code.
     *
     * @example
     * ```typescript
     * const error = new StormError({ code: 110 }, "custom");
     * console.log(error.id); // "CUSTOM-110"
     * ```
     *
     */
    get id(): string;
    /**
     * The cause of the error
     */
    get cause(): StormErrorInterface | undefined;
    /**
     * The cause of the error
     */
    set cause(cause: unknown);
    /**
     * The parsed stack traces from the raw stack string
     *
     * @returns The parsed stack traces
     */
    get stacktrace(): ParsedStacktrace[];
    /**
     * Prints a displayable/formatted stack trace
     *
     * @returns The stack trace string
     */
    get stack(): string;
    /**
     * Store the stack trace
     */
    set stack(stack: string);
    /**
     * The unformatted stack trace
     *
     * @returns The stack trace string
     */
    get originalStack(): string;
    /**
     * The unformatted stack trace
     *
     * @returns The stack trace string
     */
    set originalStack(stack: string);
    /**
     * A URL to a page that displays the error message details
     */
    get url(): string;
    /**
     * Prints the display error message string
     *
     * @param includeData - Whether to include the data in the error message
     * @returns The display error message string
     */
    toDisplay(includeData?: boolean): string;
    /**
     * Prints the error message and stack trace
     *
     * @param stacktrace - Whether to include the stack trace in the error message
     * @param includeData - Whether to include the data in the error message
     * @returns The error message and stack trace string
     */
    toString(stacktrace?: boolean, includeData?: boolean): string;
    /**
     * Converts a StormError object to a string.
     */
    [Symbol.toPrimitive](hint: "default"): string;
    /**
     * Converts a StormError object to a string.
     */
    [Symbol.toPrimitive](hint: "string"): string;
    /**
     * Converts a StormError object to a number.
     */
    [Symbol.toPrimitive](hint: "number"): number;
  }
}

declare module "storm:log/console-info" {
  export const DATE_TIME_FORMAT: Intl.DateTimeFormat;
  /**
   * Creates a new [console](https://developer.mozilla.org/en-US/docs/Web/API/console) logging adapter.
   *
   * @returns The created logging adapter.
   */
  function createAdapter(): LogAdapter;
  export default createAdapter;
}

declare module "storm:id" {
  /**
   * The ID module provides a set of utilities for generating unique identifiers.
   *
   * @module storm:id
   */
  /**
   * Generate a random string
   *
   * @param array - The array to fill with random values
   * @returns The array filled with random values
   */
  export function getRandom(array: Uint8Array): Uint8Array<ArrayBufferLike>;
  /**
   * A platform agnostic version of the [nanoid](https://github.com/ai/nanoid) package with some modifications.
   *
   * @param size - The size of the string to generate. Defaults to 21 if not provided.
   * @returns A unique identifier following the nanoid format
   */
  export function uniqueId(size?: number | undefined): string;
  /**
   * A platform agnostic version of the [nanoid](https://github.com/ai/nanoid) package with some modifications.
   *
   * @param prefix - The prefix to use for the unique identifier
   * @param size - The size of the string to generate. Defaults to 21 if not provided.
   * @returns A unique identifier following the nanoid format
   */
  export function uniqueId(prefix?: string, size?: number | undefined): string;
}

declare module "storm:meta" {
  /**
   * This module provides the runtime metadata information for the Storm Stack application.
   *
   * @module storm:meta
   */

  /**
   * Checks if a specific flag is present in the command line arguments.
   *
   * @see {@link https://github.com/sindresorhus/has-flag/blob/main/index.js}
   *
   * @param flag - The flag to check for, e.g., "color", "no-color".
   * @param argv - The command line arguments to check against. Defaults to global Deno args or process args.
   * @returns True if the flag is present, false otherwise.
   */
  export function hasFlag(flag: string, argv?: string[]): boolean;
  /**
   * Options for getting the color support level.
   */
  export type GetColorSupportLevelOptions = {
    isTTY?: boolean;
    sniffFlags?: boolean;
  };
  /**
   * Determines the color support level of the terminal.
   *
   * @param stream - The stream to check availability of (e.g., process.stdout).
   * @param options - Options for the color detection.
   * @returns The color support level (0 = no color, 1 = basic, 2 = 256 colors, 3 = true color).
   */
  export function getColorSupportLevel(
    stream: NodeJS.WriteStream & {
      fd: 1 | 2;
    },
    options?: GetColorSupportLevelOptions
  ):
    | false
    | 0
    | 2
    | 3
    | {
        level: number;
        hasBasic: boolean;
        has256: boolean;
        has16m: boolean;
      };
  /**
   * Generate a list of variables that describe the current application's runtime metadata.
   *
   * @returns An object containing the runtime metadata details.
   */
  export function createMeta(): StormNodeMeta;
  export type GetColorSupportLevelOptions = any[];
}

declare module "storm:request" {
  /**
   * The request module provides a base request class used by the Storm Stack runtime.
   *
   * @module storm:request
   */

  /**
   * A base request class used by the Storm Stack runtime.
   */
  export class StormRequest<
    TData extends Record<string, any> = Record<string, any>
  > implements StormRequestInterface<TData>
  {
    /**
     * The request identifier.
     */
    readonly id: string;
    /**
     * The headers associated with the request.
     */
    readonly headers: Record<string, any>;
    /**
     * The request created timestamp.
     */
    readonly timestamp: number;
    /**
     * The request data.
     */
    readonly data: TData;
    /**
     * Create a new request object.
     *
     * @param data - The request input data.
     */
    constructor(data: TData);
    /**
     * Merges the given data into the request.
     *
     * @param data - The data to merge into the request.
     */
    merge(data: Partial<TData>): void;
  }
}

declare module "storm:response" {
  /**
   * The response module provides the {@link StormResponse} class, which is used to represent the response of a request execution.
   *
   * @module storm:response
   */

  /**
   * A base response class used by the Storm Stack runtime.
   */
  export class StormResponse<TData extends any | StormError = any | StormError>
    implements StormResponseInterface<TData>
  {
    /**
     * Create a new response.
     *
     * @remarks
     * **IMPORTANT:** This function uses the storm context object - never use this function outside of the context wrapper/tree since the context will not be available.
     *
     * @param data - The response data
     */
    static create<TData>(data: TData): StormResponse<TData>;
    /**
     * The request headers.
     */
    readonly headers: Record<string, any>;
    /**
     * The response data.
     */
    data: TData;
    /**
     * The request identifier.
     */
    readonly requestId: string;
    /**
     * The response created timestamp.
     */
    readonly timestamp: number;
    /**
     * An indicator of whether the response was successful.
     */
    get success(): boolean;
    /**
     * Create a new response.
     *
     * @param requestId - The request identifier.
     * @param meta - The current context's metadata.
     * @param data - The response data
     */
    constructor(requestId: string, data: TData);
  }
}

declare module "storm:storage/crash-reports" {
  function createAdapter(): StorageAdapter;
  export default createAdapter;
}

declare module "storm:storage/storage" {
  function createAdapter(): StorageAdapter;
  export default createAdapter;
}

declare module "storm:storage" {
  /**
   * The storage module provides a unified storage interface for the Storm Stack runtime.
   *
   * @module storm:storage
   */

  /**
   * Creates a new storage instance.
   *
   * @remarks
   * This function initializes the storage with all configured adapters.
   *
   * @returns The {@link StormStorageInterface} storage instance with each storage adapter loaded into a slice of it's total state.
   */
  export function createStorage(): StormStorageInterface;
}

declare module "storm:context" {
  /**
   * This module provides the Storm Stack context and a hook to access it in the application.
   *
   * @module storm:context
   */

  /**
   * The global Storm context for the current application.
   *
   * @remarks
   * This interface extends the base Storm context interface with additional properties specific to the NodeJs application.
   */
  export interface StormContext extends StormContextInterface {
    /**
     * The request object for the current Storm Stack application.
     */
    request: StormRequest;
    /**
     * The root application logger for the Storm Stack application.
     */
    log: import("@storm-stack/core/runtime-types/shared/log").StormLogInterface;
    /**
     * The {@link StormStorageInterface} instance used by the Storm Stack application.
     */
    storage: import("@storm-stack/core/runtime-types/shared/storage").StormStorageInterface;
    /**
     * The environment variables for the Storm application.
     */
    env: StormEnv & Record<string, any>;
    /**
     * Environment/runtime specific application data.
     */
    meta: import("@storm-stack/core/runtime-types/node/meta").StormNodeMeta;
    /**
     * A set of disposable resources to clean up when the context is no longer needed.
     */
    readonly disposables: Set<Disposable>;
    /**
     * A set of asynchronous disposable resources to clean up when the context is no longer needed.
     */
    readonly asyncDisposables: Set<AsyncDisposable>;
  }
  /**
   * Get the Storm context for the current application.
   *
   * @param options - The options to use when getting the context.
   * @returns The Storm context for the current application.
   * @throws If the Storm context is not available.
   */
  export function useStorm(options?: ContextOptions): StormContext;
  /**
   * Wrap an application entry point with the necessary context and error handling.
   *
   * @param handler - The handler function for the application.
   * @returns A function that takes an request and returns a response or a promise of a response.
   */
  export function withContext<
    TInput extends Record<string, any> = Record<string, any>,
    TOutput = any
  >(
    handler: HandlerFunction<TInput, TOutput>
  ): (input: TInput) => Promise<StormResponse<TOutput | StormError>>;
  export type StormContext = any[];
}

declare module "storm:log/sentry-error" {
  /**
   * Creates a new [Sentry](https://sentry.io/) logging adapter.
   *
   * @returns The created {@link LogAdapter}.
   */
  function createAdapter(): LogAdapter;
  export default createAdapter;
}

declare module "storm:log/storage-info" {
  /**
   * Get a text formatter with the specified options.  Although it's flexible
   * enough to create a custom formatter, if you want more control, you can
   * create a custom formatter that satisfies the {@link TextFormatter} type
   * instead.
   *
   * For more information on the options, see {@link TextFormatterOptions}.
   *
   * By default, the formatter formats log records as follows:
   *
   * ```
   * 2023-11-14 22:13:20.000 +00:00 [INFO] Hello, world!
   * ```
   * @param options - The options for the text formatter.
   * @returns The text formatter.
   */
  export function getTextFormatter(
    options?: TextFormatterOptions
  ): TextFormatter;
  /**
   * Creates a new [Unstorage](https://unstorage.dev/) logging adapter.
   *
   * @returns The created logging adapter.
   */
  function createAdapter(): LogAdapter;
  export default createAdapter;
}

declare module "storm:log" {
  /**
   * The log module provides a unified logging interface for Storm Stack applications.
   *
   * @module storm:log
   */

  /**
   * Returns a filter that accepts log records with the specified level.
   *
   * @param level - The level to filter by. If `null`, the filter will reject all records.
   * @returns The filter.
   */
  export function getLevelFilter(level: LogLevel | null): LogFilter;
  /**
   * Parses a {@link LogLevel | log level} from a string.
   *
   * @param level - The {@link LogLevel | log level} as a string. This is case-insensitive.
   * @returns The {@link LogLevel | log level}.
   */
  export function parseLogLevel(level: string): LogLevel;
  /**
   * Checks if a string is a valid {@link LogLevel | log level}. This function can be used as a type guard to narrow the type of a string to a {@link LogLevel}.
   *
   * @param level - The {@link LogLevel | log level} as a string. This is case-sensitive.
   * @returns `true` if the string is a valid {@link LogLevel | log level}.
   */
  export function isLogLevel(level: string): level is LogLevel;
  /**
   * The StormLog class that's used for writing logs during Storm Stack applications.
   */
  export class StormLog implements StormLogInterface {
    /**
     * The list of filters applied to log records.
     *
     * @remarks
     * Filters are functions that take a {@link LogRecord} and return a boolean indicating whether the record should be logged. You can add custom filters to this list to control which log records are emitted.
     */
    readonly filters: LogFilter[];
    /**
     * The lowest log level that will be logged by this logger.
     *
     * @remarks
     * This is set to the value of the `LOG_LEVEL` configuration parameter.
     *
     * @defaultValue "info"
     */
    lowestLogLevel: LogLevel | null;
    /**
     * Create a new StormLog instance.
     *
     * @remarks
     * This constructor initializes the logger with an empty filter list and sets the lowest log level to `null`.
     */
    constructor();
    /**
     * Generates a new {@link StormLogCtx} instance and adds properties to the logger context.
     *
     * @remarks
     * This method allows you to create a new logger context with additional properties. The properties will be merged with the existing properties in the logger context.
     *
     * @param properties - The properties to add to the logger context.
     * @returns A new {@link StormLogCtx} instance with the merged properties.
     */
    with(properties: Record<string, unknown>): StormLogInterface;
    /**
     * Filters log records based on the logger's filters.
     *
     * @param record - The log record to filter.
     * @returns Whether the log record passes all filters.
     */
    filter(record: LogRecord): boolean;
    /**
     * Returns an async iterable of log adapters that match the specified log level.
     *
     * @param level - The log level to filter adapters by.
     * @returns An iterable of log adapters that match the specified log level.
     */
    adapters(level?: LogLevel): Iterable<LogAdapter>;
    /**
     * Emits a log record to all registered adapters that match the record's log level.
     *
     * @param record - The log record to emit.
     * @param bypassAdapters - A set of adapters to bypass when emitting the record.
     */
    emit(record: LogRecord, bypassAdapters?: Set<LogAdapter>): void;
    /**
     * Logs a message at the specified log level.
     *
     * @param level - The log level to use.
     * @param rawMessage - The raw message to log.
     * @param properties - The properties to include with the log message.
     * @param bypassAdapters - A set of adapters to bypass when emitting the log message.
     */
    log(
      level: LogLevel,
      rawMessage: string,
      properties: Record<string, unknown> | (() => Record<string, unknown>),
      bypassAdapters?: Set<LogAdapter>
    ): void;
    /**
     * Logs a message lazily at the specified log level.
     *
     * @param level - The log level to use.
     * @param callback - A callback function that returns the message to log.
     * @param properties - The properties to include with the log message.
     */
    logLazily(
      level: LogLevel,
      callback: LogCallback,
      properties?: Record<string, unknown>
    ): void;
    /**
     * Logs a message template at the specified log level.
     *
     * @param level - The log level to use.
     * @param messageTemplate - The message template to log.
     * @param values - The values to interpolate into the message template.
     * @param properties - The properties to include with the log message.
     */
    logTemplate(
      level: LogLevel,
      messageTemplate: TemplateStringsArray,
      values: unknown[],
      properties?: Record<string, unknown>
    ): void;
    /**
     * Logs a debug message.
     *
     * @param message - The message to log. Can be a string, a template string, or a callback function that returns the message.
     * @param values - The values to interpolate into the message template.
     */
    debug(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    /**
     * Logs an info message.
     *
     * @param message - The message to log. Can be a string, a template string, or a callback function that returns the message.
     * @param values - The values to interpolate into the message template.
     */
    info(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    /**
     * Logs a warning message.
     *
     * @param message - The message to log. Can be a string, a template string, or a callback function that returns the message.
     * @param values - The values to interpolate into the message template.
     */
    warn(
      message: TemplateStringsArray | string | LogCallback,
      ...values: unknown[]
    ): void;
    /**
     * Logs an error message.
     *
     * @param message - The message to log. Can be a string, a template string, or a callback function that returns the message.
     * @param values - The values to interpolate into the message template.
     */
    error(
      message: TemplateStringsArray | string | LogCallback | Error,
      ...values: unknown[]
    ): void;
    /**
     * Logs a fatal message.
     *
     * @param message - The message to log. Can be a string, a template string, or a callback function that returns the message.
     * @param values - The values to interpolate into the message template.
     */
    fatal(
      message: TemplateStringsArray | string | LogCallback | Error,
      ...values: unknown[]
    ): void;
    protected getStore(): Record<string, unknown>;
  }
}

declare module "storm:event" {
  /**
   * The Storm Stack event module.
   *
   * @module storm:event
   */

  /**
   * A base event class used by the Storm Stack runtime.
   */
  export class StormEvent<
    TEventType extends string = string,
    TData extends Record<string, any> = Record<string, any>
  > implements StormEventInterface<TEventType, TData>
  {
    /**
     * The event timestamp.
     */
    readonly timestamp: number;
    /**
     * The event identifier.
     */
    readonly id: string;
    /**
     * The event data object.
     */
    readonly data: TData;
    /**
     * The request identifier.
     */
    readonly requestId: string;
    /**
     * The event type.
     */
    readonly type: TEventType;
    /**
     * The event version.
     */
    readonly version: string;
    /**
     * The event label.
     *
     * @remarks
     * The label format is "{type}-v{version}"
     */
    get label(): string;
    /**
     * Creates a new event.
     *
     * @param type - The event type.
     * @param data - The event data.
     */
    constructor(type: TEventType, data: TData);
  }
}

declare module "storm:date" {
  /**
   * The Storm Stack date module provides utility functions for date manipulation and formatting
   *
   * @module storm:date
   */

  export const formats: DateFormats;
  export const locale: Locale;
  /**
   * Creates a date object using the provided value.
   *
   * @remarks
   * This function creates a date object using the provided value. If the value is `null`, it returns `null`. If the value is `undefined`, it returns the current date. If the value is a string, it parses the string as a date. If the value is a number, it treats it as a timestamp. If the value is a date object, it returns the date object.
   *
   * @example
   * ```ts
   * import { createDate } from "storm:date";
   *
   * const date = createDate("2023-10-01");
   * console.log(date.format("YYYY-MM-DD")); // Outputs: 2023-10-01
   * ```
   *
   * @param value - The value to create the date object from.
   * @returns A date object or `null` if the value is `null`.
   */
  export function createDate<
    TArg = undefined,
    TResultingDate = TArg extends null
      ? null
      : TArg extends undefined
        ? Date
        : Date | null
  >(value?: TArg): TResultingDate;
  export const type = "date-fns";
  export function is12HourCycleInCurrentLocale(): boolean;
  export function getFormatHelperText(format: string): string;
  export function parseISO(isoString: string): Date;
  export function toISO(value: Date): string;
  export function getCurrentLocaleCode(): string;
  export function addSeconds(value: Date, count: number): Date;
  export function addMinutes(value: Date, count: number): Date;
  export function addHours(value: Date, count: number): Date;
  export function addDays(value: Date, count: number): Date;
  export function addWeeks(value: Date, count: number): Date;
  export function addMonths(value: Date, count: number): Date;
  export function addYears(value: Date, count: number): Date;
  export function isValid(value: any): boolean;
  export function getDiff(
    value: Date,
    comparing: Date | string,
    unit?: TimeUnit
  ): number;
  export function isAfter(value: Date, comparing: Date): boolean;
  export function isBefore(value: Date, comparing: Date): boolean;
  export function startOfDay(value: Date): Date;
  export function endOfDay(value: Date): Date;
  export function getHours(value: Date): number;
  export function setHours(value: Date, count: number): Date;
  export function setMinutes(value: Date, count: number): Date;
  export function getSeconds(value: Date): number;
  export function setSeconds(value: Date, count: number): Date;
  export function isSameDay(value: Date, comparing: Date): boolean;
  export function isSameMonth(value: Date, comparing: Date): boolean;
  export function isSameYear(value: Date, comparing: Date): boolean;
  export function isSameHour(value: Date, comparing: Date): boolean;
  export function startOfYear(value: Date): Date;
  export function endOfYear(value: Date): Date;
  export function startOfMonth(value: Date): Date;
  export function endOfMonth(value: Date): Date;
  export function startOfWeek(value: Date): Date;
  export function endOfWeek(value: Date): Date;
  export function getYear(value: Date): number;
  export function setYear(value: Date, count: number): Date;
  export function toJsDate(value: Date): Date;
  export function parse(value: string, formatString: string): Date | null;
  export function format(date: Date, formatKey: keyof DateFormats): string;
  export function formatByString(date: Date, formatString: string): string;
  export function isEqual(date: any, comparing: any): boolean;
  export function isNull(date: Date): date is never;
  export function isAfterDay(date: Date, value: Date): boolean;
  export function isBeforeDay(date: Date, value: Date): boolean;
  export function isBeforeYear(date: Date, value: Date): boolean;
  export function isBeforeMonth(value: Date, comparing: Date): boolean;
  export function isAfterMonth(value: Date, comparing: Date): boolean;
  export function isAfterYear(date: Date, value: Date): boolean;
  export function isWithinRange(
    date: Date,
    [start, end]: [Date, Date]
  ): boolean;
  export function formatNumber(numberToFormat: string): string;
  export function getMinutes(date: Date): number;
  export function getDate(date: Date): number;
  export function setDate(date: Date, count: number): Date;
  export function getWeek(date: Date): number;
  export function getMonth(date: Date): number;
  export function getDaysInMonth(date: Date): number;
  export function setMonth(date: Date, count: number): Date;
  export function getMeridiemText(meridiem: "am" | "pm"): "AM" | "PM";
  export function getNextMonth(date: Date): Date;
  export function getPreviousMonth(date: Date): Date;
  export function getMonthArray(date: Date): Date[];
  export function mergeDateAndTime(date: Date, time: Date): Date;
  export function getWeekdays(): string[];
  export function getWeekArray(date: Date): Date[][];
  export function getYearRange(start: Date, end: Date): Date[];
}

declare module "storm:cli" {
  export type CLIRequestData = {
    argv: string[];
  };
  export type ColorName =
    | "reset"
    | "bold"
    | "dim"
    | "italic"
    | "underline"
    | "overline"
    | "inverse"
    | "hidden"
    | "strikethrough"
    | "black"
    | "red"
    | "green"
    | "yellow"
    | "blue"
    | "magenta"
    | "cyan"
    | "white"
    | "blackBright"
    | "gray"
    | "grey"
    | "redBright"
    | "greenBright"
    | "yellowBright"
    | "blueBright"
    | "magentaBright"
    | "cyanBright"
    | "whiteBright"
    | "bgBlack"
    | "bgRed"
    | "bgGreen"
    | "bgYellow"
    | "bgBlue"
    | "bgMagenta"
    | "bgCyan"
    | "bgWhite"
    | "bgBlackBright"
    | "bgGray"
    | "bgGrey"
    | "bgRedBright"
    | "bgGreenBright"
    | "bgYellowBright"
    | "bgBlueBright"
    | "bgMagentaBright"
    | "bgCyanBright"
    | "bgWhiteBright"
    | "background"
    | "bgBackground"
    | "foreground"
    | "bgForeground"
    | "brand"
    | "bgBrand"
    | "alternate"
    | "bgAlternate"
    | "help"
    | "bgHelp"
    | "success"
    | "bgSuccess"
    | "info"
    | "bgInfo"
    | "warning"
    | "bgWarning"
    | "danger"
    | "bgDanger"
    | "fatal"
    | "bgFatal"
    | "link"
    | "bgLink"
    | "positive"
    | "bgPositive"
    | "negative"
    | "bgNegative";
  /**
   * An object containing functions for coloring text. Each function corresponds to a terminal color. See {@link ColorName} for available colors.
   */
  export const colors: Record<ColorName, (text: string | number) => string>;
  /**
   * Gets a color function by name, with an option for a fallback color if the requested color is not found.
   *
   * @param color - The name of the color function to get. See {@link ColorName}.
   * @param fallback - The name of the fallback color function if the requested color is not found. See {@link ColorName}.
   * @returns The color function that corresponds to the requested color, or the fallback color function.
   */
  export function getColor(
    color: ColorName,
    fallback?: ColorName
  ): (text: string | number) => string;
  /**
   * Formats a message for display in the CLI.
   *
   * @param text - The message text to format.
   * @param color - The color to use for the message (default: "brand").
   * @param title - The title to use for the message (default: "Message").
   * @param icon - An optional icon to display with the message.
   * @returns The formatted message string.
   */
  export function formatMessage(
    text: string,
    color?: ColorName,
    title?: string,
    icon?: string,
    stretch?: boolean
  ): string;
  /**
   * Shows a fatal error message in the CLI.
   *
   * @param details - The fatal error details to display.
   */
  export function showFatal(details: string | Error): void;
  /**
   * Shows an error message in the CLI.
   *
   * @param details - The error details to display.
   */
  export function showError(details: string | Error): void;
  /**
   * Shows a warning message in the CLI.
   *
   * @param details - The warning details to display.
   */
  export function showWarning(text: string): void;
  /**
   * Shows a info message in the CLI.
   *
   * @param details - The info details to display.
   */
  export function showInfo(text: string): void;
  /**
   * Shows a help message in the CLI.
   *
   * @param details - The help details to display.
   */
  export function showHelp(text: string): void;
  /**
   * Shows a success message in the CLI.
   *
   * @param details - The success details to display.
   */
  export function showSuccess(text: string): void;
  type LinkOptions = {
    /**
     * Whether to use colored text for the link.
     *
     * @defaultValue "link"
     */
    color?: ColorName | false;
    /**
     * The target for the link. Can be either "stdout" or "stderr".
     *
     * @defaultValue "stdout"
     */
    target?: "stdout" | "stderr";
    /**
     * A fallback function to handle the link in environments that do not support it.
     */
    fallback?: (url: string, text?: string) => string;
  };
  /**
   * Create a link to a URL in the console.
   *
   * @param url - The URL to link to.
   * @param text - The text to display for the link. If not provided, the URL will be used as the text.
   * @param options - Options to use when formatting the link.
   * @returns A terminal link
   */
  export function link(
    url: string,
    text?: string,
    options?: LinkOptions
  ): string;
  /**
   * Strips ANSI escape codes from a string.
   *
   * @param text - The string to strip ANSI codes from.
   * @returns The string without ANSI codes.
   */
  export function stripAnsi(text: string): string;
  /**
   * Renders a CLI banner with the specified title.
   *
   * @param title - The title to display in the banner.
   * @param description - The description to display in the banner.
   * @returns The rendered banner as a string.
   *
   * @internal
   */
  export function renderBanner(title: string, description: string): string;
  /**
   * Renders a CLI footer with the application details
   *
   * @param title - The title to display in the footer.
   * @param description - The description to display in the footer.
   * @returns The rendered footer as a string.
   *
   * @internal
   */
  export function renderFooter(): string;
  interface SelectOption {
    label: string;
    value: string;
    hint?: string;
  }
  const CANCEL_SYMBOL: unique symbol;
  interface PromptCommonOptions {
    /**
     * Specify how to handle a cancelled prompt (e.g. by pressing Ctrl+C).
     *
     * @remarks
     * The list of valid cancel strategies include:
     * - `"default"` - Resolve the promise with the `default` value or `initial` value.
     * - `"undefined`" - Resolve the promise with `undefined`.
     * - `"null"` - Resolve the promise with `null`.
     * - `"symbol"` - Resolve the promise with a symbol `Symbol.for("cancel")`.
     * - `"reject"`  - Reject the promise with an error.
     *
     * @defaultValue "default"
     */
    cancel?: "reject" | "default" | "undefined" | "null" | "symbol";
  }
  export type TextPromptOptions = PromptCommonOptions & {
    /**
     * Specifies the prompt type as text.
     *
     * @defaultValue "text"
     */
    type?: "text";
    /**
     * The default text value.
     */
    default?: string;
    /**
     * A placeholder text displayed in the prompt.
     */
    placeholder?: string;
    /**
     * The initial text value.
     */
    initial?: string;
  };
  export type ConfirmPromptOptions = PromptCommonOptions & {
    /**
     * Specifies the prompt type as confirm.
     */
    type: "confirm";
    /**
     * The initial value for the confirm prompt.
     */
    initial?: boolean;
  };
  export type SelectPromptOptions = PromptCommonOptions & {
    /**
     * Specifies the prompt type as select.
     */
    type: "select";
    /**
     * The initial value for the select prompt.
     */
    initial?: string;
    /**
     * The options to select from. See {@link SelectOption}.
     */
    options: (string | SelectOption)[];
  };
  export type MultiSelectPromptOptions = PromptCommonOptions & {
    /**
     * Specifies the prompt type as multiselect.
     */
    type: "multiselect";
    /**
     * The options to select from. See {@link SelectOption}.
     */
    initial?: string[];
    /**
     * The options to select from. See {@link SelectOption}.
     */
    options: (string | SelectOption)[];
    /**
     * Whether the prompt requires at least one selection.
     */
    required?: boolean;
  };
  /**
   * Defines a combined type for all prompt options.
   */
  export type PromptOptions =
    | TextPromptOptions
    | ConfirmPromptOptions
    | SelectPromptOptions
    | MultiSelectPromptOptions;
  type inferPromptReturnType<T extends PromptOptions> =
    T extends TextPromptOptions
      ? string
      : T extends ConfirmPromptOptions
        ? boolean
        : T extends SelectPromptOptions
          ? T["options"][number] extends SelectOption
            ? T["options"][number]["value"]
            : T["options"][number]
          : T extends MultiSelectPromptOptions
            ? T["options"]
            : unknown;
  type inferPromptCancelReturnType<T extends PromptOptions> = T extends {
    cancel: "reject";
  }
    ? never
    : T extends {
          cancel: "default";
        }
      ? inferPromptReturnType<T>
      : T extends {
            cancel: "undefined";
          }
        ? undefined
        : T extends {
              cancel: "null";
            }
          ? null
          : T extends {
                cancel: "symbol";
              }
            ? typeof CANCEL_SYMBOL
            : inferPromptReturnType<T>;
  /**
   * Asynchronously prompts the user for input based on specified options.
   * Supports text, confirm, select and multi-select prompts.
   *
   * @param message - The message to display in the prompt.
   * @param opts - The prompt options. See {@link PromptOptions}.
   * @returns A promise that resolves with the user's response, the type of which is inferred from the options. See {@link inferPromptReturnType}.
   */
  export function prompt<
    _ = any,
    __ = any,
    T extends PromptOptions = TextPromptOptions
  >(
    message: string,
    opts?: PromptOptions
  ): Promise<inferPromptReturnType<T> | inferPromptCancelReturnType<T>>;
  export function parseArgs(args: any[], opts: any): any;
  export {};
  export type CLIRequestData = any[];
  export type ColorName = any[];
  export type TextPromptOptions = any[];
  export type ConfirmPromptOptions = any[];
  export type SelectPromptOptions = any[];
  export type MultiSelectPromptOptions = any[];
  export type PromptOptions = any[];
}

declare module "storm:app" {
  /**
   * Wrap an application entry point with the necessary context and error handling.
   *
   * @param handler - The handler function for the application.
   * @returns A function that takes an request and returns a response or a promise of a response.
   */
  export function createCLIApp<
    TInput extends CLIRequestData = CLIRequestData,
    TOutput = any
  >(
    handler: HandlerFunction<TInput, TOutput>
  ): (input: TInput) => Promise<StormResponse<StormError | unknown>>;
}

declare const $storm: import("storm:context").StormContext;
