/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

import { deserialize } from "@deepkit/type";
import { withContext } from "../../runtime/app";
import {
  colors,
  parseArgs,
  prompt,
  renderBanner,
  renderFooter
} from "../../runtime/cli";
import { isInteractive, isMinimal } from "../../runtime/env";
import handle from "./../../../src/commands/add/index";
import { renderUsage } from "./usage";

export interface AddPayload {
  help: boolean;
  version: boolean;
  interactive: boolean;
  noInteractive: boolean;
  noBanner: boolean;
  verbose: boolean;
  file: string;
  type: string;
}

const handleCommand = withContext<AddPayload>(handle);

/**
 * The entry point for the Add command.
 */
async function handler() {
  try {
    if (process.argv.length > 3) {
      const command = process.argv[2];
      if (command && !command.startsWith("-")) {
        if (command.toLowerCase() === "page") {
          const handle = await import("./page").then(m => m.default);
          return handle();
        }

        console.error(
          ` ${colors.red("✘")} ${colors.white(`Unknown command: ${colors.bold(command || "<none>")}`)}`
        );
        console.log("");
        console.log(renderUsage("full"));
        console.log("");
        console.log(renderFooter());
        console.log("");

        return;
      }
    }

    const args = parseArgs(process.argv.slice(2), {
      boolean: [
        "help",
        "h",
        "?",
        "version",
        "v",
        "interactive",
        "i",
        "interact",
        "no-interactive",
        "no-interact",
        "no-banner",
        "",
        "verbose",
        "v"
      ],
      alias: {
        help: ["help", "HELP", "h", "H", "?", "?"],
        version: ["version", "VERSION", "v", "V"],
        interactive: [
          "interactive",
          "INTERACTIVE",
          "i",
          "I",
          "interact",
          "INTERACT"
        ],
        noInteractive: [
          "no-interactive",
          "NO-INTERACTIVE",
          "no-interact",
          "NO-INTERACT"
        ],
        noBanner: ["no-banner", "NO-BANNER"],
        verbose: ["verbose", "VERBOSE", "v", "V"],
        file: ["file", "FILE", "f", "F"],
        type: ["type", "TYPE", "t", "T"]
      }
    });

    if (args["version"] || args["v"]) {
      console.log($storm.vars.APP_VERSION);
    } else {
      const isVerbose =
        args["verbose"] ?? Boolean(process.env.EXAMPLES_CLI_VERBOSE);
      const isPromptEnabled =
        args["interactive"] !== false &&
        args["no-interactive"] !== true &&
        Boolean(process.env.EXAMPLES_CLI_INTERACTIVE) &&
        isInteractive &&
        !isMinimal;

      if (args["no-banner"] !== true && !isMinimal) {
        console.log(
          renderBanner("Add Command", "Add an item to the file system.")
        );
        console.log("");
      }

      if (args["help"] || args["h"] || args["?"]) {
        console.log(renderUsage("full"));
        console.log("");
        console.log(renderFooter());
        console.log("");
      } else {
        if (isVerbose) {
          console.log(
            colors.dim(
              ` > Writing verbose output to console - as a result of the ${args["verbose"] ? 'user provided "verbose" option' : "EXAMPLES_CLI_VERBOSE environment variable"} `
            )
          );
          console.log("");

          if (isPromptEnabled) {
            console.log(colors.dim(" > Running in interactive mode..."));
          } else {
            console.log(colors.dim(" > Running in non-interactive mode..."));
          }
          console.log("");
        }

        if (args["file"] === undefined && process.env.EXAMPLES_CLI_FILE) {
          args["file"] = process.env.EXAMPLES_CLI_FILE;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the file option to ${process.env.EXAMPLES_CLI_FILE} (via the EXAMPLES_CLI_FILE environment variable) `
              )
            );
          }
        }

        if (args["type"] === undefined && process.env.EXAMPLES_CLI_TYPE) {
          args["type"] = process.env.EXAMPLES_CLI_TYPE;
          if (isVerbose) {
            console.log(
              colors.dim(
                ` > Setting the type option to ${process.env.EXAMPLES_CLI_TYPE} (via the EXAMPLES_CLI_TYPE environment variable) `
              )
            );
          }
        }

        if (args["file"] === undefined) {
          if (isPromptEnabled) {
            args["file"] = await prompt<string>(`Please provide a File value`, {
              type: "text",
              initial: "server.ts",
              default: "server.ts",
              placeholder: "The file to add to the file system"
            });
          }

          if (args["file"] === undefined) {
            args["file"] = "server.ts";
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the file option to "server.ts" (via it's default value) `
                )
              );
            }
          }
        }

        if (args["type"] === undefined) {
          if (isPromptEnabled) {
            args["type"] = await prompt<string>(`Please provide a Type value`, {
              type: "text",
              initial: "server",
              default: "server",
              placeholder: "The type of the file"
            });
          }

          if (args["type"] === undefined) {
            args["type"] = "server";
            if (isVerbose) {
              console.log(
                colors.dim(
                  ` > Setting the type option to "server" (via it's default value) `
                )
              );
            }
          }
        }

        await handleCommand(deserialize<AddPayload>(args));
      }
    }
  } catch (err) {
    console.error(
      ` ${colors.red("✘")} ${colors.white(`Error occurred while processing Add command.`)}`
    );
  }
}

export default handler;
