/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

/// <reference types="../../../../dist/packages/types" />
/// <reference types="../../../../dist/packages/types/node" />

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

declare global {
  const _StormEvent: (typeof import("../runtime/event"))["StormEvent"];

  class StormEvent<TEventType extends string = string, TEventData = any>
   extends _StormEvent<TEventType, TEventData> {
    /**
    * Creates a new event.
    *
    * @param type - The event type.
    * @param data - The event data.
    */
    public constructor(
      type: TEventType,
      data: TEventData
    ) {
      super(type, data);
    }
  }

  const build: StormBuildInfo;
  const runtime: StormRuntimeInfo;
  const paths: StormEnvPaths;

  const useStorm: () => StormContext<StormVariables>;
  const STORM_ASYNC_CONTEXT: StormContext<StormVariables>;
}

export {};
