/* eslint-disable */
// biome-ignore lint: disable
// prettier-ignore

/// <reference types="@storm-stack/plugin-node/types" />

// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically

declare module "storm:init" {
  export { };
}

declare module "storm:app" {
  const builder: (typeof import("../runtime/app"))["builder"];
  export { builder };
}

declare module "storm:context" {
  const getBuildInfo: (typeof import("../runtime/context"))["getBuildInfo"];
  const getRuntimeInfo: (typeof import("../runtime/context"))["getRuntimeInfo"];
  const useStorm: (typeof import("../runtime/context"))["useStorm"];
  const STORM_ASYNC_CONTEXT: (typeof import("../runtime/context"))["STORM_ASYNC_CONTEXT"];

  export { STORM_ASYNC_CONTEXT, getBuildInfo, getRuntimeInfo, useStorm };
}

declare module "storm:storage" {
  const storage: (typeof import("../runtime/storage"))["storage"];
  export { storage };
}

declare module "storm:event" {
  const _StormEvent: (typeof import("../runtime/event"))["StormEvent"];

  class StormEvent<
    TEventType extends string = string,
    TEventData = any
  > extends _StormEvent<TEventType, TEventData> {
    /**
     * Creates a new event.
     *
     * @param type - The event type.
     * @param data - The event data.
     */
    public constructor(type: TEventType, data: TEventData) {
      super(type, data);
    }
  }

  export { StormEvent };
}
