name: "Continuous Integration"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches:
      - "main"
      - "next"
      - "beta"
      - "experimental"

jobs:
  ci:
    name: Continuous Integration
    if: github.repository == 'storm-software/storm-stack' && (github.ref ==
      'refs/heads/main' || github.ref == 'refs/heads/next' || github.ref ==
      'refs/heads/beta' || github.ref == 'refs/heads/experimental')
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: storm-software/storm-ops/.github/workflows/ci-reusable.yml@main
    with:
      tag: ${{ inputs.tag }}
      package-manager: pnpm
      package-manager-version: 9.10.0
      storm-bot: Stormie-Bot
    secrets: inherit
