name: "CLA Check"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

env:
  CI: true
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.STORM_BOT_CARGO_TOKEN }}

jobs:
  cla:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: contributor-assistant/github-action@v2.6.1
        if: |
          github.event_name == 'pull_request_target' ||
          github.event.comment.body == 'recheck' ||
          github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
        with:
          path-to-document: docs/CLA.md
          path-to-signatures: tools/signatures/cla.json
          branch: main
          allowlist: dependabot[bot],stormie-bot
          remote-organization-name: storm-software
          remote-repository-name: storm-cloud
