name: "Code Review"
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  CI: true
  NX_VERBOSE_LOGGING: true
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main

