# https://stackoverflow.com/q/70664840/590396
name: Dependabot auto-approve
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

env:
  CI: true
  NX_VERBOSE_LOGGING: true
  STORM_WORKER: stormie-bot
  STORM_REPOSITORY: https://github.com/storm-software/storm-stack
  STORM_WORKSPACE_ROOT: ${{ github.workspace }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_ACTOR: ${{env.STORM_WORKER}}
          GITHUB_TOKEN: ${{secrets.STORMIE_GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
