---
name: Sync labels

on:
  push:
    branches:
      - main
      - canary
      - experimental
    paths:
      - .github/labels.yml

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  SKIP_ENV_VALIDATION: true

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
